/*
 * VMaaS Webapp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.20.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vmaas
// RpmPkgNamesRequest struct for RpmPkgNamesRequest
type RpmPkgNamesRequest struct {
	RpmNameList []string `json:"rpm_name_list"`
	ContentSetList []string `json:"content_set_list,omitempty"`
}
