/*
 * VMaaS Webapp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.20.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vmaas
// SrpmPkgNamesRequest struct for SrpmPkgNamesRequest
type SrpmPkgNamesRequest struct {
	SrpmNameList []string `json:"srpm_name_list"`
	ContentSetList []string `json:"content_set_list,omitempty"`
}
