/*
 * VMaaS Webapp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.20.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vmaas
// RpmPkgNamesResponse struct for RpmPkgNamesResponse
type RpmPkgNamesResponse struct {
	LastChange interface{} `json:"last_change,omitempty"`
	RpmNameList map[string][]string `json:"rpm_name_list,omitempty"`
}
