/*
 * VMaaS Webapp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.20.4
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vmaas

import (
	"encoding/json"
)

// PkgtreeRequest struct for PkgtreeRequest
type PkgtreeRequest struct {
	PackageNameList []string `json:"package_name_list"`
}

// NewPkgtreeRequest instantiates a new PkgtreeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPkgtreeRequest(packageNameList []string, ) *PkgtreeRequest {
	this := PkgtreeRequest{}
	this.PackageNameList = packageNameList
	return &this
}

// NewPkgtreeRequestWithDefaults instantiates a new PkgtreeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPkgtreeRequestWithDefaults() *PkgtreeRequest {
	this := PkgtreeRequest{}
	return &this
}

// GetPackageNameList returns the PackageNameList field value
func (o *PkgtreeRequest) GetPackageNameList() []string {
	if o == nil  {
		var ret []string
		return ret
	}

	return o.PackageNameList
}

// GetPackageNameListOk returns a tuple with the PackageNameList field value
// and a boolean to check if the value has been set.
func (o *PkgtreeRequest) GetPackageNameListOk() (*[]string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PackageNameList, true
}

// SetPackageNameList sets field value
func (o *PkgtreeRequest) SetPackageNameList(v []string) {
	o.PackageNameList = v
}

func (o PkgtreeRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["package_name_list"] = o.PackageNameList
	}
	return json.Marshal(toSerialize)
}

type NullablePkgtreeRequest struct {
	value *PkgtreeRequest
	isSet bool
}

func (v NullablePkgtreeRequest) Get() *PkgtreeRequest {
	return v.value
}

func (v *NullablePkgtreeRequest) Set(val *PkgtreeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePkgtreeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePkgtreeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePkgtreeRequest(val *PkgtreeRequest) *NullablePkgtreeRequest {
	return &NullablePkgtreeRequest{value: val, isSet: true}
}

func (v NullablePkgtreeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePkgtreeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


