/*
 * VMaaS Webapp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.5.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vmaas

import (
	"encoding/json"
)

// PkgtreeRequest struct for PkgtreeRequest
type PkgtreeRequest struct {
	PackageNameList []string `json:"package_name_list"`
	// Include content from \"third party\" repositories into the response, disabled by default.
	ThirdParty *bool `json:"third_party,omitempty"`
}

// NewPkgtreeRequest instantiates a new PkgtreeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPkgtreeRequest(packageNameList []string, ) *PkgtreeRequest {
	this := PkgtreeRequest{}
	this.PackageNameList = packageNameList
	var thirdParty bool = false
	this.ThirdParty = &thirdParty
	return &this
}

// NewPkgtreeRequestWithDefaults instantiates a new PkgtreeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPkgtreeRequestWithDefaults() *PkgtreeRequest {
	this := PkgtreeRequest{}
	var thirdParty bool = false
	this.ThirdParty = &thirdParty
	return &this
}

// GetPackageNameList returns the PackageNameList field value
func (o *PkgtreeRequest) GetPackageNameList() []string {
	if o == nil  {
		var ret []string
		return ret
	}

	return o.PackageNameList
}

// GetPackageNameListOk returns a tuple with the PackageNameList field value
// and a boolean to check if the value has been set.
func (o *PkgtreeRequest) GetPackageNameListOk() (*[]string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PackageNameList, true
}

// SetPackageNameList sets field value
func (o *PkgtreeRequest) SetPackageNameList(v []string) {
	o.PackageNameList = v
}

// GetThirdParty returns the ThirdParty field value if set, zero value otherwise.
func (o *PkgtreeRequest) GetThirdParty() bool {
	if o == nil || o.ThirdParty == nil {
		var ret bool
		return ret
	}
	return *o.ThirdParty
}

// GetThirdPartyOk returns a tuple with the ThirdParty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PkgtreeRequest) GetThirdPartyOk() (*bool, bool) {
	if o == nil || o.ThirdParty == nil {
		return nil, false
	}
	return o.ThirdParty, true
}

// HasThirdParty returns a boolean if a field has been set.
func (o *PkgtreeRequest) HasThirdParty() bool {
	if o != nil && o.ThirdParty != nil {
		return true
	}

	return false
}

// SetThirdParty gets a reference to the given bool and assigns it to the ThirdParty field.
func (o *PkgtreeRequest) SetThirdParty(v bool) {
	o.ThirdParty = &v
}

func (o PkgtreeRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["package_name_list"] = o.PackageNameList
	}
	if o.ThirdParty != nil {
		toSerialize["third_party"] = o.ThirdParty
	}
	return json.Marshal(toSerialize)
}

type NullablePkgtreeRequest struct {
	value *PkgtreeRequest
	isSet bool
}

func (v NullablePkgtreeRequest) Get() *PkgtreeRequest {
	return v.value
}

func (v *NullablePkgtreeRequest) Set(val *PkgtreeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePkgtreeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePkgtreeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePkgtreeRequest(val *PkgtreeRequest) *NullablePkgtreeRequest {
	return &NullablePkgtreeRequest{value: val, isSet: true}
}

func (v NullablePkgtreeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePkgtreeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


