/*
 * VMaaS Webapp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.12.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vmaas
// PatchesResponse struct for PatchesResponse
type PatchesResponse struct {
	ErrataList []string `json:"errata_list,omitempty"`
}
