/*
 * Insights Host Inventory REST Interface
 *
 * REST interface for the Insights Platform Host Inventory application.
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package inventory

import (
	"encoding/json"
)

// CanonicalFactsInAllOf struct for CanonicalFactsInAllOf
type CanonicalFactsInAllOf struct {
	BiosUuid *string `json:"bios_uuid,omitempty"`
	Fqdn *string `json:"fqdn,omitempty"`
	InsightsId *string `json:"insights_id,omitempty"`
	IpAddresses *[]string `json:"ip_addresses,omitempty"`
	MacAddresses *[]string `json:"mac_addresses,omitempty"`
	ProviderId *string `json:"provider_id,omitempty"`
	ProviderType *string `json:"provider_type,omitempty"`
	SatelliteId *string `json:"satellite_id,omitempty"`
	SubscriptionManagerId *string `json:"subscription_manager_id,omitempty"`
}

// NewCanonicalFactsInAllOf instantiates a new CanonicalFactsInAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCanonicalFactsInAllOf() *CanonicalFactsInAllOf {
	this := CanonicalFactsInAllOf{}
	return &this
}

// NewCanonicalFactsInAllOfWithDefaults instantiates a new CanonicalFactsInAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCanonicalFactsInAllOfWithDefaults() *CanonicalFactsInAllOf {
	this := CanonicalFactsInAllOf{}
	return &this
}

// GetBiosUuid returns the BiosUuid field value if set, zero value otherwise.
func (o *CanonicalFactsInAllOf) GetBiosUuid() string {
	if o == nil || o.BiosUuid == nil {
		var ret string
		return ret
	}
	return *o.BiosUuid
}

// GetBiosUuidOk returns a tuple with the BiosUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanonicalFactsInAllOf) GetBiosUuidOk() (*string, bool) {
	if o == nil || o.BiosUuid == nil {
		return nil, false
	}
	return o.BiosUuid, true
}

// HasBiosUuid returns a boolean if a field has been set.
func (o *CanonicalFactsInAllOf) HasBiosUuid() bool {
	if o != nil && o.BiosUuid != nil {
		return true
	}

	return false
}

// SetBiosUuid gets a reference to the given string and assigns it to the BiosUuid field.
func (o *CanonicalFactsInAllOf) SetBiosUuid(v string) {
	o.BiosUuid = &v
}

// GetFqdn returns the Fqdn field value if set, zero value otherwise.
func (o *CanonicalFactsInAllOf) GetFqdn() string {
	if o == nil || o.Fqdn == nil {
		var ret string
		return ret
	}
	return *o.Fqdn
}

// GetFqdnOk returns a tuple with the Fqdn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanonicalFactsInAllOf) GetFqdnOk() (*string, bool) {
	if o == nil || o.Fqdn == nil {
		return nil, false
	}
	return o.Fqdn, true
}

// HasFqdn returns a boolean if a field has been set.
func (o *CanonicalFactsInAllOf) HasFqdn() bool {
	if o != nil && o.Fqdn != nil {
		return true
	}

	return false
}

// SetFqdn gets a reference to the given string and assigns it to the Fqdn field.
func (o *CanonicalFactsInAllOf) SetFqdn(v string) {
	o.Fqdn = &v
}

// GetInsightsId returns the InsightsId field value if set, zero value otherwise.
func (o *CanonicalFactsInAllOf) GetInsightsId() string {
	if o == nil || o.InsightsId == nil {
		var ret string
		return ret
	}
	return *o.InsightsId
}

// GetInsightsIdOk returns a tuple with the InsightsId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanonicalFactsInAllOf) GetInsightsIdOk() (*string, bool) {
	if o == nil || o.InsightsId == nil {
		return nil, false
	}
	return o.InsightsId, true
}

// HasInsightsId returns a boolean if a field has been set.
func (o *CanonicalFactsInAllOf) HasInsightsId() bool {
	if o != nil && o.InsightsId != nil {
		return true
	}

	return false
}

// SetInsightsId gets a reference to the given string and assigns it to the InsightsId field.
func (o *CanonicalFactsInAllOf) SetInsightsId(v string) {
	o.InsightsId = &v
}

// GetIpAddresses returns the IpAddresses field value if set, zero value otherwise.
func (o *CanonicalFactsInAllOf) GetIpAddresses() []string {
	if o == nil || o.IpAddresses == nil {
		var ret []string
		return ret
	}
	return *o.IpAddresses
}

// GetIpAddressesOk returns a tuple with the IpAddresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanonicalFactsInAllOf) GetIpAddressesOk() (*[]string, bool) {
	if o == nil || o.IpAddresses == nil {
		return nil, false
	}
	return o.IpAddresses, true
}

// HasIpAddresses returns a boolean if a field has been set.
func (o *CanonicalFactsInAllOf) HasIpAddresses() bool {
	if o != nil && o.IpAddresses != nil {
		return true
	}

	return false
}

// SetIpAddresses gets a reference to the given []string and assigns it to the IpAddresses field.
func (o *CanonicalFactsInAllOf) SetIpAddresses(v []string) {
	o.IpAddresses = &v
}

// GetMacAddresses returns the MacAddresses field value if set, zero value otherwise.
func (o *CanonicalFactsInAllOf) GetMacAddresses() []string {
	if o == nil || o.MacAddresses == nil {
		var ret []string
		return ret
	}
	return *o.MacAddresses
}

// GetMacAddressesOk returns a tuple with the MacAddresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanonicalFactsInAllOf) GetMacAddressesOk() (*[]string, bool) {
	if o == nil || o.MacAddresses == nil {
		return nil, false
	}
	return o.MacAddresses, true
}

// HasMacAddresses returns a boolean if a field has been set.
func (o *CanonicalFactsInAllOf) HasMacAddresses() bool {
	if o != nil && o.MacAddresses != nil {
		return true
	}

	return false
}

// SetMacAddresses gets a reference to the given []string and assigns it to the MacAddresses field.
func (o *CanonicalFactsInAllOf) SetMacAddresses(v []string) {
	o.MacAddresses = &v
}

// GetProviderId returns the ProviderId field value if set, zero value otherwise.
func (o *CanonicalFactsInAllOf) GetProviderId() string {
	if o == nil || o.ProviderId == nil {
		var ret string
		return ret
	}
	return *o.ProviderId
}

// GetProviderIdOk returns a tuple with the ProviderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanonicalFactsInAllOf) GetProviderIdOk() (*string, bool) {
	if o == nil || o.ProviderId == nil {
		return nil, false
	}
	return o.ProviderId, true
}

// HasProviderId returns a boolean if a field has been set.
func (o *CanonicalFactsInAllOf) HasProviderId() bool {
	if o != nil && o.ProviderId != nil {
		return true
	}

	return false
}

// SetProviderId gets a reference to the given string and assigns it to the ProviderId field.
func (o *CanonicalFactsInAllOf) SetProviderId(v string) {
	o.ProviderId = &v
}

// GetProviderType returns the ProviderType field value if set, zero value otherwise.
func (o *CanonicalFactsInAllOf) GetProviderType() string {
	if o == nil || o.ProviderType == nil {
		var ret string
		return ret
	}
	return *o.ProviderType
}

// GetProviderTypeOk returns a tuple with the ProviderType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanonicalFactsInAllOf) GetProviderTypeOk() (*string, bool) {
	if o == nil || o.ProviderType == nil {
		return nil, false
	}
	return o.ProviderType, true
}

// HasProviderType returns a boolean if a field has been set.
func (o *CanonicalFactsInAllOf) HasProviderType() bool {
	if o != nil && o.ProviderType != nil {
		return true
	}

	return false
}

// SetProviderType gets a reference to the given string and assigns it to the ProviderType field.
func (o *CanonicalFactsInAllOf) SetProviderType(v string) {
	o.ProviderType = &v
}

// GetSatelliteId returns the SatelliteId field value if set, zero value otherwise.
func (o *CanonicalFactsInAllOf) GetSatelliteId() string {
	if o == nil || o.SatelliteId == nil {
		var ret string
		return ret
	}
	return *o.SatelliteId
}

// GetSatelliteIdOk returns a tuple with the SatelliteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanonicalFactsInAllOf) GetSatelliteIdOk() (*string, bool) {
	if o == nil || o.SatelliteId == nil {
		return nil, false
	}
	return o.SatelliteId, true
}

// HasSatelliteId returns a boolean if a field has been set.
func (o *CanonicalFactsInAllOf) HasSatelliteId() bool {
	if o != nil && o.SatelliteId != nil {
		return true
	}

	return false
}

// SetSatelliteId gets a reference to the given string and assigns it to the SatelliteId field.
func (o *CanonicalFactsInAllOf) SetSatelliteId(v string) {
	o.SatelliteId = &v
}

// GetSubscriptionManagerId returns the SubscriptionManagerId field value if set, zero value otherwise.
func (o *CanonicalFactsInAllOf) GetSubscriptionManagerId() string {
	if o == nil || o.SubscriptionManagerId == nil {
		var ret string
		return ret
	}
	return *o.SubscriptionManagerId
}

// GetSubscriptionManagerIdOk returns a tuple with the SubscriptionManagerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanonicalFactsInAllOf) GetSubscriptionManagerIdOk() (*string, bool) {
	if o == nil || o.SubscriptionManagerId == nil {
		return nil, false
	}
	return o.SubscriptionManagerId, true
}

// HasSubscriptionManagerId returns a boolean if a field has been set.
func (o *CanonicalFactsInAllOf) HasSubscriptionManagerId() bool {
	if o != nil && o.SubscriptionManagerId != nil {
		return true
	}

	return false
}

// SetSubscriptionManagerId gets a reference to the given string and assigns it to the SubscriptionManagerId field.
func (o *CanonicalFactsInAllOf) SetSubscriptionManagerId(v string) {
	o.SubscriptionManagerId = &v
}

func (o CanonicalFactsInAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.BiosUuid != nil {
		toSerialize["bios_uuid"] = o.BiosUuid
	}
	if o.Fqdn != nil {
		toSerialize["fqdn"] = o.Fqdn
	}
	if o.InsightsId != nil {
		toSerialize["insights_id"] = o.InsightsId
	}
	if o.IpAddresses != nil {
		toSerialize["ip_addresses"] = o.IpAddresses
	}
	if o.MacAddresses != nil {
		toSerialize["mac_addresses"] = o.MacAddresses
	}
	if o.ProviderId != nil {
		toSerialize["provider_id"] = o.ProviderId
	}
	if o.ProviderType != nil {
		toSerialize["provider_type"] = o.ProviderType
	}
	if o.SatelliteId != nil {
		toSerialize["satellite_id"] = o.SatelliteId
	}
	if o.SubscriptionManagerId != nil {
		toSerialize["subscription_manager_id"] = o.SubscriptionManagerId
	}
	return json.Marshal(toSerialize)
}

type NullableCanonicalFactsInAllOf struct {
	value *CanonicalFactsInAllOf
	isSet bool
}

func (v NullableCanonicalFactsInAllOf) Get() *CanonicalFactsInAllOf {
	return v.value
}

func (v *NullableCanonicalFactsInAllOf) Set(val *CanonicalFactsInAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableCanonicalFactsInAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableCanonicalFactsInAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCanonicalFactsInAllOf(val *CanonicalFactsInAllOf) *NullableCanonicalFactsInAllOf {
	return &NullableCanonicalFactsInAllOf{value: val, isSet: true}
}

func (v NullableCanonicalFactsInAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCanonicalFactsInAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


