/*
 * Insights Host Inventory REST Interface
 *
 * REST interface for the Insights Platform Host Inventory application.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventory
// SystemProfileSpecYamlSystemProfileRhsm Object for subscription-manager details
type SystemProfileSpecYamlSystemProfileRhsm struct {
	// System release set by subscription-manager
	Version string `json:"version,omitempty"`
}
