/*
 * Insights Host Inventory REST Interface
 *
 * REST interface for the Insights Platform Host Inventory application.
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package inventory

import (
	"encoding/json"
)

// SystemProfileRhsm Object for subscription-manager details
type SystemProfileRhsm struct {
	// System release set by subscription-manager
	Version *string `json:"version,omitempty"`
}

// NewSystemProfileRhsm instantiates a new SystemProfileRhsm object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemProfileRhsm() *SystemProfileRhsm {
	this := SystemProfileRhsm{}
	return &this
}

// NewSystemProfileRhsmWithDefaults instantiates a new SystemProfileRhsm object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemProfileRhsmWithDefaults() *SystemProfileRhsm {
	this := SystemProfileRhsm{}
	return &this
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *SystemProfileRhsm) GetVersion() string {
	if o == nil || o.Version == nil {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfileRhsm) GetVersionOk() (*string, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *SystemProfileRhsm) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *SystemProfileRhsm) SetVersion(v string) {
	o.Version = &v
}

func (o SystemProfileRhsm) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	return json.Marshal(toSerialize)
}

type NullableSystemProfileRhsm struct {
	value *SystemProfileRhsm
	isSet bool
}

func (v NullableSystemProfileRhsm) Get() *SystemProfileRhsm {
	return v.value
}

func (v *NullableSystemProfileRhsm) Set(val *SystemProfileRhsm) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemProfileRhsm) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemProfileRhsm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemProfileRhsm(val *SystemProfileRhsm) *NullableSystemProfileRhsm {
	return &NullableSystemProfileRhsm{value: val, isSet: true}
}

func (v NullableSystemProfileRhsm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemProfileRhsm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


