/*
 * Insights Host Inventory REST Interface
 *
 * REST interface for the Insights Platform Host Inventory application.
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package inventory

import (
	"encoding/json"
)

// TagCountOutAllOf struct for TagCountOutAllOf
type TagCountOutAllOf struct {
	// The list of tags on the systems
	Results *map[string]int32 `json:"results,omitempty"`
}

// NewTagCountOutAllOf instantiates a new TagCountOutAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagCountOutAllOf() *TagCountOutAllOf {
	this := TagCountOutAllOf{}
	return &this
}

// NewTagCountOutAllOfWithDefaults instantiates a new TagCountOutAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagCountOutAllOfWithDefaults() *TagCountOutAllOf {
	this := TagCountOutAllOf{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *TagCountOutAllOf) GetResults() map[string]int32 {
	if o == nil || o.Results == nil {
		var ret map[string]int32
		return ret
	}
	return *o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TagCountOutAllOf) GetResultsOk() (*map[string]int32, bool) {
	if o == nil || o.Results == nil {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *TagCountOutAllOf) HasResults() bool {
	if o != nil && o.Results != nil {
		return true
	}

	return false
}

// SetResults gets a reference to the given map[string]int32 and assigns it to the Results field.
func (o *TagCountOutAllOf) SetResults(v map[string]int32) {
	o.Results = &v
}

func (o TagCountOutAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Results != nil {
		toSerialize["results"] = o.Results
	}
	return json.Marshal(toSerialize)
}

type NullableTagCountOutAllOf struct {
	value *TagCountOutAllOf
	isSet bool
}

func (v NullableTagCountOutAllOf) Get() *TagCountOutAllOf {
	return v.value
}

func (v *NullableTagCountOutAllOf) Set(val *TagCountOutAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableTagCountOutAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableTagCountOutAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagCountOutAllOf(val *TagCountOutAllOf) *NullableTagCountOutAllOf {
	return &NullableTagCountOutAllOf{value: val, isSet: true}
}

func (v NullableTagCountOutAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagCountOutAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


