/*
 * Insights Host Inventory REST Interface
 *
 * REST interface for the Insights Platform Host Inventory application.
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package inventory

import (
	"encoding/json"
)

// SystemProfile Representation of the system profile fields
type SystemProfile struct {
	Ansible *SystemProfileAnsible `json:"ansible,omitempty"`
	Arch *string `json:"arch,omitempty"`
	BiosReleaseDate *string `json:"bios_release_date,omitempty"`
	BiosVendor *string `json:"bios_vendor,omitempty"`
	BiosVersion *string `json:"bios_version,omitempty"`
	CapturedDate *string `json:"captured_date,omitempty"`
	CloudProvider *string `json:"cloud_provider,omitempty"`
	CoresPerSocket *int32 `json:"cores_per_socket,omitempty"`
	CpuFlags *[]string `json:"cpu_flags,omitempty"`
	// The cpu model name
	CpuModel *string `json:"cpu_model,omitempty"`
	DiskDevices *[]SystemProfileDiskDevice `json:"disk_devices,omitempty"`
	DnfModules *[]SystemProfileDnfModule `json:"dnf_modules,omitempty"`
	EnabledServices *[]string `json:"enabled_services,omitempty"`
	GpgPubkeys *[]string `json:"gpg_pubkeys,omitempty"`
	// Indicates whether greenboot detected a rolled back update on an edge device.
	GreenbootFallbackDetected *bool `json:"greenboot_fallback_detected,omitempty"`
	// Indicates the greenboot status of an edge device.
	GreenbootStatus *string `json:"greenboot_status,omitempty"`
	// Indicates the type of host.
	HostType *string `json:"host_type,omitempty"`
	InfrastructureType *string `json:"infrastructure_type,omitempty"`
	InfrastructureVendor *string `json:"infrastructure_vendor,omitempty"`
	// The version number of insights client. supports wildcards
	InsightsClientVersion *string `json:"insights_client_version,omitempty"`
	InsightsEggVersion *string `json:"insights_egg_version,omitempty"`
	InstalledPackages *[]string `json:"installed_packages,omitempty"`
	InstalledPackagesDelta *[]string `json:"installed_packages_delta,omitempty"`
	InstalledProducts *[]SystemProfileInstalledProduct `json:"installed_products,omitempty"`
	InstalledServices *[]string `json:"installed_services,omitempty"`
	// Indicates whether the host is part of a marketplace install from AWS, Azure, etc.
	IsMarketplace *bool `json:"is_marketplace,omitempty"`
	KatelloAgentRunning *bool `json:"katello_agent_running,omitempty"`
	KernelModules *[]string `json:"kernel_modules,omitempty"`
	LastBootTime *string `json:"last_boot_time,omitempty"`
	Mssql *SystemProfileMssql `json:"mssql,omitempty"`
	NetworkInterfaces *[]SystemProfileNetworkInterface `json:"network_interfaces,omitempty"`
	NumberOfCpus *int32 `json:"number_of_cpus,omitempty"`
	NumberOfSockets *int32 `json:"number_of_sockets,omitempty"`
	OperatingSystem *SystemProfileOperatingSystem `json:"operating_system,omitempty"`
	// The kernel version represented with a three, optionally four, number scheme.
	OsKernelVersion *string `json:"os_kernel_version,omitempty"`
	OsRelease *string `json:"os_release,omitempty"`
	// A UUID associated with the host's RHSM certificate
	OwnerId *string `json:"owner_id,omitempty"`
	// A UUID associated with a cloud_connector
	RhcClientId *string `json:"rhc_client_id,omitempty"`
	// A UUID associated with the config manager state
	RhcConfigState *string `json:"rhc_config_state,omitempty"`
	Rhsm *SystemProfileRhsm `json:"rhsm,omitempty"`
	// The list of deployments on the system as reported by rpm-ostree status --json
	RpmOstreeDeployments *[]SystemProfileRpmOstreeDeployments `json:"rpm_ostree_deployments,omitempty"`
	RunningProcesses *[]string `json:"running_processes,omitempty"`
	// The instance number of the SAP HANA system (a two-digit number between 00 and 99)
	SapInstanceNumber *string `json:"sap_instance_number,omitempty"`
	SapSids *[]string `json:"sap_sids,omitempty"`
	// Indicates if SAP is installed on the system
	SapSystem *bool `json:"sap_system,omitempty"`
	// The version of the SAP HANA lifecycle management program
	SapVersion *string `json:"sap_version,omitempty"`
	SatelliteManaged *bool `json:"satellite_managed,omitempty"`
	// The SELinux mode provided in the config file
	SelinuxConfigFile *string `json:"selinux_config_file,omitempty"`
	// The current SELinux mode, either enforcing, permissive, or disabled
	SelinuxCurrentMode *string `json:"selinux_current_mode,omitempty"`
	SubscriptionAutoAttach *string `json:"subscription_auto_attach,omitempty"`
	SubscriptionStatus *string `json:"subscription_status,omitempty"`
	SystemMemoryBytes *int64 `json:"system_memory_bytes,omitempty"`
	SystemPurpose *SystemProfileSystemPurpose `json:"system_purpose,omitempty"`
	// Current profile resulting from command tuned-adm active
	TunedProfile *string `json:"tuned_profile,omitempty"`
	YumRepos *[]SystemProfileYumRepo `json:"yum_repos,omitempty"`
}

// NewSystemProfile instantiates a new SystemProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemProfile() *SystemProfile {
	this := SystemProfile{}
	return &this
}

// NewSystemProfileWithDefaults instantiates a new SystemProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemProfileWithDefaults() *SystemProfile {
	this := SystemProfile{}
	return &this
}

// GetAnsible returns the Ansible field value if set, zero value otherwise.
func (o *SystemProfile) GetAnsible() SystemProfileAnsible {
	if o == nil || o.Ansible == nil {
		var ret SystemProfileAnsible
		return ret
	}
	return *o.Ansible
}

// GetAnsibleOk returns a tuple with the Ansible field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetAnsibleOk() (*SystemProfileAnsible, bool) {
	if o == nil || o.Ansible == nil {
		return nil, false
	}
	return o.Ansible, true
}

// HasAnsible returns a boolean if a field has been set.
func (o *SystemProfile) HasAnsible() bool {
	if o != nil && o.Ansible != nil {
		return true
	}

	return false
}

// SetAnsible gets a reference to the given SystemProfileAnsible and assigns it to the Ansible field.
func (o *SystemProfile) SetAnsible(v SystemProfileAnsible) {
	o.Ansible = &v
}

// GetArch returns the Arch field value if set, zero value otherwise.
func (o *SystemProfile) GetArch() string {
	if o == nil || o.Arch == nil {
		var ret string
		return ret
	}
	return *o.Arch
}

// GetArchOk returns a tuple with the Arch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetArchOk() (*string, bool) {
	if o == nil || o.Arch == nil {
		return nil, false
	}
	return o.Arch, true
}

// HasArch returns a boolean if a field has been set.
func (o *SystemProfile) HasArch() bool {
	if o != nil && o.Arch != nil {
		return true
	}

	return false
}

// SetArch gets a reference to the given string and assigns it to the Arch field.
func (o *SystemProfile) SetArch(v string) {
	o.Arch = &v
}

// GetBiosReleaseDate returns the BiosReleaseDate field value if set, zero value otherwise.
func (o *SystemProfile) GetBiosReleaseDate() string {
	if o == nil || o.BiosReleaseDate == nil {
		var ret string
		return ret
	}
	return *o.BiosReleaseDate
}

// GetBiosReleaseDateOk returns a tuple with the BiosReleaseDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetBiosReleaseDateOk() (*string, bool) {
	if o == nil || o.BiosReleaseDate == nil {
		return nil, false
	}
	return o.BiosReleaseDate, true
}

// HasBiosReleaseDate returns a boolean if a field has been set.
func (o *SystemProfile) HasBiosReleaseDate() bool {
	if o != nil && o.BiosReleaseDate != nil {
		return true
	}

	return false
}

// SetBiosReleaseDate gets a reference to the given string and assigns it to the BiosReleaseDate field.
func (o *SystemProfile) SetBiosReleaseDate(v string) {
	o.BiosReleaseDate = &v
}

// GetBiosVendor returns the BiosVendor field value if set, zero value otherwise.
func (o *SystemProfile) GetBiosVendor() string {
	if o == nil || o.BiosVendor == nil {
		var ret string
		return ret
	}
	return *o.BiosVendor
}

// GetBiosVendorOk returns a tuple with the BiosVendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetBiosVendorOk() (*string, bool) {
	if o == nil || o.BiosVendor == nil {
		return nil, false
	}
	return o.BiosVendor, true
}

// HasBiosVendor returns a boolean if a field has been set.
func (o *SystemProfile) HasBiosVendor() bool {
	if o != nil && o.BiosVendor != nil {
		return true
	}

	return false
}

// SetBiosVendor gets a reference to the given string and assigns it to the BiosVendor field.
func (o *SystemProfile) SetBiosVendor(v string) {
	o.BiosVendor = &v
}

// GetBiosVersion returns the BiosVersion field value if set, zero value otherwise.
func (o *SystemProfile) GetBiosVersion() string {
	if o == nil || o.BiosVersion == nil {
		var ret string
		return ret
	}
	return *o.BiosVersion
}

// GetBiosVersionOk returns a tuple with the BiosVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetBiosVersionOk() (*string, bool) {
	if o == nil || o.BiosVersion == nil {
		return nil, false
	}
	return o.BiosVersion, true
}

// HasBiosVersion returns a boolean if a field has been set.
func (o *SystemProfile) HasBiosVersion() bool {
	if o != nil && o.BiosVersion != nil {
		return true
	}

	return false
}

// SetBiosVersion gets a reference to the given string and assigns it to the BiosVersion field.
func (o *SystemProfile) SetBiosVersion(v string) {
	o.BiosVersion = &v
}

// GetCapturedDate returns the CapturedDate field value if set, zero value otherwise.
func (o *SystemProfile) GetCapturedDate() string {
	if o == nil || o.CapturedDate == nil {
		var ret string
		return ret
	}
	return *o.CapturedDate
}

// GetCapturedDateOk returns a tuple with the CapturedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetCapturedDateOk() (*string, bool) {
	if o == nil || o.CapturedDate == nil {
		return nil, false
	}
	return o.CapturedDate, true
}

// HasCapturedDate returns a boolean if a field has been set.
func (o *SystemProfile) HasCapturedDate() bool {
	if o != nil && o.CapturedDate != nil {
		return true
	}

	return false
}

// SetCapturedDate gets a reference to the given string and assigns it to the CapturedDate field.
func (o *SystemProfile) SetCapturedDate(v string) {
	o.CapturedDate = &v
}

// GetCloudProvider returns the CloudProvider field value if set, zero value otherwise.
func (o *SystemProfile) GetCloudProvider() string {
	if o == nil || o.CloudProvider == nil {
		var ret string
		return ret
	}
	return *o.CloudProvider
}

// GetCloudProviderOk returns a tuple with the CloudProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetCloudProviderOk() (*string, bool) {
	if o == nil || o.CloudProvider == nil {
		return nil, false
	}
	return o.CloudProvider, true
}

// HasCloudProvider returns a boolean if a field has been set.
func (o *SystemProfile) HasCloudProvider() bool {
	if o != nil && o.CloudProvider != nil {
		return true
	}

	return false
}

// SetCloudProvider gets a reference to the given string and assigns it to the CloudProvider field.
func (o *SystemProfile) SetCloudProvider(v string) {
	o.CloudProvider = &v
}

// GetCoresPerSocket returns the CoresPerSocket field value if set, zero value otherwise.
func (o *SystemProfile) GetCoresPerSocket() int32 {
	if o == nil || o.CoresPerSocket == nil {
		var ret int32
		return ret
	}
	return *o.CoresPerSocket
}

// GetCoresPerSocketOk returns a tuple with the CoresPerSocket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetCoresPerSocketOk() (*int32, bool) {
	if o == nil || o.CoresPerSocket == nil {
		return nil, false
	}
	return o.CoresPerSocket, true
}

// HasCoresPerSocket returns a boolean if a field has been set.
func (o *SystemProfile) HasCoresPerSocket() bool {
	if o != nil && o.CoresPerSocket != nil {
		return true
	}

	return false
}

// SetCoresPerSocket gets a reference to the given int32 and assigns it to the CoresPerSocket field.
func (o *SystemProfile) SetCoresPerSocket(v int32) {
	o.CoresPerSocket = &v
}

// GetCpuFlags returns the CpuFlags field value if set, zero value otherwise.
func (o *SystemProfile) GetCpuFlags() []string {
	if o == nil || o.CpuFlags == nil {
		var ret []string
		return ret
	}
	return *o.CpuFlags
}

// GetCpuFlagsOk returns a tuple with the CpuFlags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetCpuFlagsOk() (*[]string, bool) {
	if o == nil || o.CpuFlags == nil {
		return nil, false
	}
	return o.CpuFlags, true
}

// HasCpuFlags returns a boolean if a field has been set.
func (o *SystemProfile) HasCpuFlags() bool {
	if o != nil && o.CpuFlags != nil {
		return true
	}

	return false
}

// SetCpuFlags gets a reference to the given []string and assigns it to the CpuFlags field.
func (o *SystemProfile) SetCpuFlags(v []string) {
	o.CpuFlags = &v
}

// GetCpuModel returns the CpuModel field value if set, zero value otherwise.
func (o *SystemProfile) GetCpuModel() string {
	if o == nil || o.CpuModel == nil {
		var ret string
		return ret
	}
	return *o.CpuModel
}

// GetCpuModelOk returns a tuple with the CpuModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetCpuModelOk() (*string, bool) {
	if o == nil || o.CpuModel == nil {
		return nil, false
	}
	return o.CpuModel, true
}

// HasCpuModel returns a boolean if a field has been set.
func (o *SystemProfile) HasCpuModel() bool {
	if o != nil && o.CpuModel != nil {
		return true
	}

	return false
}

// SetCpuModel gets a reference to the given string and assigns it to the CpuModel field.
func (o *SystemProfile) SetCpuModel(v string) {
	o.CpuModel = &v
}

// GetDiskDevices returns the DiskDevices field value if set, zero value otherwise.
func (o *SystemProfile) GetDiskDevices() []SystemProfileDiskDevice {
	if o == nil || o.DiskDevices == nil {
		var ret []SystemProfileDiskDevice
		return ret
	}
	return *o.DiskDevices
}

// GetDiskDevicesOk returns a tuple with the DiskDevices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetDiskDevicesOk() (*[]SystemProfileDiskDevice, bool) {
	if o == nil || o.DiskDevices == nil {
		return nil, false
	}
	return o.DiskDevices, true
}

// HasDiskDevices returns a boolean if a field has been set.
func (o *SystemProfile) HasDiskDevices() bool {
	if o != nil && o.DiskDevices != nil {
		return true
	}

	return false
}

// SetDiskDevices gets a reference to the given []SystemProfileDiskDevice and assigns it to the DiskDevices field.
func (o *SystemProfile) SetDiskDevices(v []SystemProfileDiskDevice) {
	o.DiskDevices = &v
}

// GetDnfModules returns the DnfModules field value if set, zero value otherwise.
func (o *SystemProfile) GetDnfModules() []SystemProfileDnfModule {
	if o == nil || o.DnfModules == nil {
		var ret []SystemProfileDnfModule
		return ret
	}
	return *o.DnfModules
}

// GetDnfModulesOk returns a tuple with the DnfModules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetDnfModulesOk() (*[]SystemProfileDnfModule, bool) {
	if o == nil || o.DnfModules == nil {
		return nil, false
	}
	return o.DnfModules, true
}

// HasDnfModules returns a boolean if a field has been set.
func (o *SystemProfile) HasDnfModules() bool {
	if o != nil && o.DnfModules != nil {
		return true
	}

	return false
}

// SetDnfModules gets a reference to the given []SystemProfileDnfModule and assigns it to the DnfModules field.
func (o *SystemProfile) SetDnfModules(v []SystemProfileDnfModule) {
	o.DnfModules = &v
}

// GetEnabledServices returns the EnabledServices field value if set, zero value otherwise.
func (o *SystemProfile) GetEnabledServices() []string {
	if o == nil || o.EnabledServices == nil {
		var ret []string
		return ret
	}
	return *o.EnabledServices
}

// GetEnabledServicesOk returns a tuple with the EnabledServices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetEnabledServicesOk() (*[]string, bool) {
	if o == nil || o.EnabledServices == nil {
		return nil, false
	}
	return o.EnabledServices, true
}

// HasEnabledServices returns a boolean if a field has been set.
func (o *SystemProfile) HasEnabledServices() bool {
	if o != nil && o.EnabledServices != nil {
		return true
	}

	return false
}

// SetEnabledServices gets a reference to the given []string and assigns it to the EnabledServices field.
func (o *SystemProfile) SetEnabledServices(v []string) {
	o.EnabledServices = &v
}

// GetGpgPubkeys returns the GpgPubkeys field value if set, zero value otherwise.
func (o *SystemProfile) GetGpgPubkeys() []string {
	if o == nil || o.GpgPubkeys == nil {
		var ret []string
		return ret
	}
	return *o.GpgPubkeys
}

// GetGpgPubkeysOk returns a tuple with the GpgPubkeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetGpgPubkeysOk() (*[]string, bool) {
	if o == nil || o.GpgPubkeys == nil {
		return nil, false
	}
	return o.GpgPubkeys, true
}

// HasGpgPubkeys returns a boolean if a field has been set.
func (o *SystemProfile) HasGpgPubkeys() bool {
	if o != nil && o.GpgPubkeys != nil {
		return true
	}

	return false
}

// SetGpgPubkeys gets a reference to the given []string and assigns it to the GpgPubkeys field.
func (o *SystemProfile) SetGpgPubkeys(v []string) {
	o.GpgPubkeys = &v
}

// GetGreenbootFallbackDetected returns the GreenbootFallbackDetected field value if set, zero value otherwise.
func (o *SystemProfile) GetGreenbootFallbackDetected() bool {
	if o == nil || o.GreenbootFallbackDetected == nil {
		var ret bool
		return ret
	}
	return *o.GreenbootFallbackDetected
}

// GetGreenbootFallbackDetectedOk returns a tuple with the GreenbootFallbackDetected field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetGreenbootFallbackDetectedOk() (*bool, bool) {
	if o == nil || o.GreenbootFallbackDetected == nil {
		return nil, false
	}
	return o.GreenbootFallbackDetected, true
}

// HasGreenbootFallbackDetected returns a boolean if a field has been set.
func (o *SystemProfile) HasGreenbootFallbackDetected() bool {
	if o != nil && o.GreenbootFallbackDetected != nil {
		return true
	}

	return false
}

// SetGreenbootFallbackDetected gets a reference to the given bool and assigns it to the GreenbootFallbackDetected field.
func (o *SystemProfile) SetGreenbootFallbackDetected(v bool) {
	o.GreenbootFallbackDetected = &v
}

// GetGreenbootStatus returns the GreenbootStatus field value if set, zero value otherwise.
func (o *SystemProfile) GetGreenbootStatus() string {
	if o == nil || o.GreenbootStatus == nil {
		var ret string
		return ret
	}
	return *o.GreenbootStatus
}

// GetGreenbootStatusOk returns a tuple with the GreenbootStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetGreenbootStatusOk() (*string, bool) {
	if o == nil || o.GreenbootStatus == nil {
		return nil, false
	}
	return o.GreenbootStatus, true
}

// HasGreenbootStatus returns a boolean if a field has been set.
func (o *SystemProfile) HasGreenbootStatus() bool {
	if o != nil && o.GreenbootStatus != nil {
		return true
	}

	return false
}

// SetGreenbootStatus gets a reference to the given string and assigns it to the GreenbootStatus field.
func (o *SystemProfile) SetGreenbootStatus(v string) {
	o.GreenbootStatus = &v
}

// GetHostType returns the HostType field value if set, zero value otherwise.
func (o *SystemProfile) GetHostType() string {
	if o == nil || o.HostType == nil {
		var ret string
		return ret
	}
	return *o.HostType
}

// GetHostTypeOk returns a tuple with the HostType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetHostTypeOk() (*string, bool) {
	if o == nil || o.HostType == nil {
		return nil, false
	}
	return o.HostType, true
}

// HasHostType returns a boolean if a field has been set.
func (o *SystemProfile) HasHostType() bool {
	if o != nil && o.HostType != nil {
		return true
	}

	return false
}

// SetHostType gets a reference to the given string and assigns it to the HostType field.
func (o *SystemProfile) SetHostType(v string) {
	o.HostType = &v
}

// GetInfrastructureType returns the InfrastructureType field value if set, zero value otherwise.
func (o *SystemProfile) GetInfrastructureType() string {
	if o == nil || o.InfrastructureType == nil {
		var ret string
		return ret
	}
	return *o.InfrastructureType
}

// GetInfrastructureTypeOk returns a tuple with the InfrastructureType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetInfrastructureTypeOk() (*string, bool) {
	if o == nil || o.InfrastructureType == nil {
		return nil, false
	}
	return o.InfrastructureType, true
}

// HasInfrastructureType returns a boolean if a field has been set.
func (o *SystemProfile) HasInfrastructureType() bool {
	if o != nil && o.InfrastructureType != nil {
		return true
	}

	return false
}

// SetInfrastructureType gets a reference to the given string and assigns it to the InfrastructureType field.
func (o *SystemProfile) SetInfrastructureType(v string) {
	o.InfrastructureType = &v
}

// GetInfrastructureVendor returns the InfrastructureVendor field value if set, zero value otherwise.
func (o *SystemProfile) GetInfrastructureVendor() string {
	if o == nil || o.InfrastructureVendor == nil {
		var ret string
		return ret
	}
	return *o.InfrastructureVendor
}

// GetInfrastructureVendorOk returns a tuple with the InfrastructureVendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetInfrastructureVendorOk() (*string, bool) {
	if o == nil || o.InfrastructureVendor == nil {
		return nil, false
	}
	return o.InfrastructureVendor, true
}

// HasInfrastructureVendor returns a boolean if a field has been set.
func (o *SystemProfile) HasInfrastructureVendor() bool {
	if o != nil && o.InfrastructureVendor != nil {
		return true
	}

	return false
}

// SetInfrastructureVendor gets a reference to the given string and assigns it to the InfrastructureVendor field.
func (o *SystemProfile) SetInfrastructureVendor(v string) {
	o.InfrastructureVendor = &v
}

// GetInsightsClientVersion returns the InsightsClientVersion field value if set, zero value otherwise.
func (o *SystemProfile) GetInsightsClientVersion() string {
	if o == nil || o.InsightsClientVersion == nil {
		var ret string
		return ret
	}
	return *o.InsightsClientVersion
}

// GetInsightsClientVersionOk returns a tuple with the InsightsClientVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetInsightsClientVersionOk() (*string, bool) {
	if o == nil || o.InsightsClientVersion == nil {
		return nil, false
	}
	return o.InsightsClientVersion, true
}

// HasInsightsClientVersion returns a boolean if a field has been set.
func (o *SystemProfile) HasInsightsClientVersion() bool {
	if o != nil && o.InsightsClientVersion != nil {
		return true
	}

	return false
}

// SetInsightsClientVersion gets a reference to the given string and assigns it to the InsightsClientVersion field.
func (o *SystemProfile) SetInsightsClientVersion(v string) {
	o.InsightsClientVersion = &v
}

// GetInsightsEggVersion returns the InsightsEggVersion field value if set, zero value otherwise.
func (o *SystemProfile) GetInsightsEggVersion() string {
	if o == nil || o.InsightsEggVersion == nil {
		var ret string
		return ret
	}
	return *o.InsightsEggVersion
}

// GetInsightsEggVersionOk returns a tuple with the InsightsEggVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetInsightsEggVersionOk() (*string, bool) {
	if o == nil || o.InsightsEggVersion == nil {
		return nil, false
	}
	return o.InsightsEggVersion, true
}

// HasInsightsEggVersion returns a boolean if a field has been set.
func (o *SystemProfile) HasInsightsEggVersion() bool {
	if o != nil && o.InsightsEggVersion != nil {
		return true
	}

	return false
}

// SetInsightsEggVersion gets a reference to the given string and assigns it to the InsightsEggVersion field.
func (o *SystemProfile) SetInsightsEggVersion(v string) {
	o.InsightsEggVersion = &v
}

// GetInstalledPackages returns the InstalledPackages field value if set, zero value otherwise.
func (o *SystemProfile) GetInstalledPackages() []string {
	if o == nil || o.InstalledPackages == nil {
		var ret []string
		return ret
	}
	return *o.InstalledPackages
}

// GetInstalledPackagesOk returns a tuple with the InstalledPackages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetInstalledPackagesOk() (*[]string, bool) {
	if o == nil || o.InstalledPackages == nil {
		return nil, false
	}
	return o.InstalledPackages, true
}

// HasInstalledPackages returns a boolean if a field has been set.
func (o *SystemProfile) HasInstalledPackages() bool {
	if o != nil && o.InstalledPackages != nil {
		return true
	}

	return false
}

// SetInstalledPackages gets a reference to the given []string and assigns it to the InstalledPackages field.
func (o *SystemProfile) SetInstalledPackages(v []string) {
	o.InstalledPackages = &v
}

// GetInstalledPackagesDelta returns the InstalledPackagesDelta field value if set, zero value otherwise.
func (o *SystemProfile) GetInstalledPackagesDelta() []string {
	if o == nil || o.InstalledPackagesDelta == nil {
		var ret []string
		return ret
	}
	return *o.InstalledPackagesDelta
}

// GetInstalledPackagesDeltaOk returns a tuple with the InstalledPackagesDelta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetInstalledPackagesDeltaOk() (*[]string, bool) {
	if o == nil || o.InstalledPackagesDelta == nil {
		return nil, false
	}
	return o.InstalledPackagesDelta, true
}

// HasInstalledPackagesDelta returns a boolean if a field has been set.
func (o *SystemProfile) HasInstalledPackagesDelta() bool {
	if o != nil && o.InstalledPackagesDelta != nil {
		return true
	}

	return false
}

// SetInstalledPackagesDelta gets a reference to the given []string and assigns it to the InstalledPackagesDelta field.
func (o *SystemProfile) SetInstalledPackagesDelta(v []string) {
	o.InstalledPackagesDelta = &v
}

// GetInstalledProducts returns the InstalledProducts field value if set, zero value otherwise.
func (o *SystemProfile) GetInstalledProducts() []SystemProfileInstalledProduct {
	if o == nil || o.InstalledProducts == nil {
		var ret []SystemProfileInstalledProduct
		return ret
	}
	return *o.InstalledProducts
}

// GetInstalledProductsOk returns a tuple with the InstalledProducts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetInstalledProductsOk() (*[]SystemProfileInstalledProduct, bool) {
	if o == nil || o.InstalledProducts == nil {
		return nil, false
	}
	return o.InstalledProducts, true
}

// HasInstalledProducts returns a boolean if a field has been set.
func (o *SystemProfile) HasInstalledProducts() bool {
	if o != nil && o.InstalledProducts != nil {
		return true
	}

	return false
}

// SetInstalledProducts gets a reference to the given []SystemProfileInstalledProduct and assigns it to the InstalledProducts field.
func (o *SystemProfile) SetInstalledProducts(v []SystemProfileInstalledProduct) {
	o.InstalledProducts = &v
}

// GetInstalledServices returns the InstalledServices field value if set, zero value otherwise.
func (o *SystemProfile) GetInstalledServices() []string {
	if o == nil || o.InstalledServices == nil {
		var ret []string
		return ret
	}
	return *o.InstalledServices
}

// GetInstalledServicesOk returns a tuple with the InstalledServices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetInstalledServicesOk() (*[]string, bool) {
	if o == nil || o.InstalledServices == nil {
		return nil, false
	}
	return o.InstalledServices, true
}

// HasInstalledServices returns a boolean if a field has been set.
func (o *SystemProfile) HasInstalledServices() bool {
	if o != nil && o.InstalledServices != nil {
		return true
	}

	return false
}

// SetInstalledServices gets a reference to the given []string and assigns it to the InstalledServices field.
func (o *SystemProfile) SetInstalledServices(v []string) {
	o.InstalledServices = &v
}

// GetIsMarketplace returns the IsMarketplace field value if set, zero value otherwise.
func (o *SystemProfile) GetIsMarketplace() bool {
	if o == nil || o.IsMarketplace == nil {
		var ret bool
		return ret
	}
	return *o.IsMarketplace
}

// GetIsMarketplaceOk returns a tuple with the IsMarketplace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetIsMarketplaceOk() (*bool, bool) {
	if o == nil || o.IsMarketplace == nil {
		return nil, false
	}
	return o.IsMarketplace, true
}

// HasIsMarketplace returns a boolean if a field has been set.
func (o *SystemProfile) HasIsMarketplace() bool {
	if o != nil && o.IsMarketplace != nil {
		return true
	}

	return false
}

// SetIsMarketplace gets a reference to the given bool and assigns it to the IsMarketplace field.
func (o *SystemProfile) SetIsMarketplace(v bool) {
	o.IsMarketplace = &v
}

// GetKatelloAgentRunning returns the KatelloAgentRunning field value if set, zero value otherwise.
func (o *SystemProfile) GetKatelloAgentRunning() bool {
	if o == nil || o.KatelloAgentRunning == nil {
		var ret bool
		return ret
	}
	return *o.KatelloAgentRunning
}

// GetKatelloAgentRunningOk returns a tuple with the KatelloAgentRunning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetKatelloAgentRunningOk() (*bool, bool) {
	if o == nil || o.KatelloAgentRunning == nil {
		return nil, false
	}
	return o.KatelloAgentRunning, true
}

// HasKatelloAgentRunning returns a boolean if a field has been set.
func (o *SystemProfile) HasKatelloAgentRunning() bool {
	if o != nil && o.KatelloAgentRunning != nil {
		return true
	}

	return false
}

// SetKatelloAgentRunning gets a reference to the given bool and assigns it to the KatelloAgentRunning field.
func (o *SystemProfile) SetKatelloAgentRunning(v bool) {
	o.KatelloAgentRunning = &v
}

// GetKernelModules returns the KernelModules field value if set, zero value otherwise.
func (o *SystemProfile) GetKernelModules() []string {
	if o == nil || o.KernelModules == nil {
		var ret []string
		return ret
	}
	return *o.KernelModules
}

// GetKernelModulesOk returns a tuple with the KernelModules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetKernelModulesOk() (*[]string, bool) {
	if o == nil || o.KernelModules == nil {
		return nil, false
	}
	return o.KernelModules, true
}

// HasKernelModules returns a boolean if a field has been set.
func (o *SystemProfile) HasKernelModules() bool {
	if o != nil && o.KernelModules != nil {
		return true
	}

	return false
}

// SetKernelModules gets a reference to the given []string and assigns it to the KernelModules field.
func (o *SystemProfile) SetKernelModules(v []string) {
	o.KernelModules = &v
}

// GetLastBootTime returns the LastBootTime field value if set, zero value otherwise.
func (o *SystemProfile) GetLastBootTime() string {
	if o == nil || o.LastBootTime == nil {
		var ret string
		return ret
	}
	return *o.LastBootTime
}

// GetLastBootTimeOk returns a tuple with the LastBootTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetLastBootTimeOk() (*string, bool) {
	if o == nil || o.LastBootTime == nil {
		return nil, false
	}
	return o.LastBootTime, true
}

// HasLastBootTime returns a boolean if a field has been set.
func (o *SystemProfile) HasLastBootTime() bool {
	if o != nil && o.LastBootTime != nil {
		return true
	}

	return false
}

// SetLastBootTime gets a reference to the given string and assigns it to the LastBootTime field.
func (o *SystemProfile) SetLastBootTime(v string) {
	o.LastBootTime = &v
}

// GetMssql returns the Mssql field value if set, zero value otherwise.
func (o *SystemProfile) GetMssql() SystemProfileMssql {
	if o == nil || o.Mssql == nil {
		var ret SystemProfileMssql
		return ret
	}
	return *o.Mssql
}

// GetMssqlOk returns a tuple with the Mssql field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetMssqlOk() (*SystemProfileMssql, bool) {
	if o == nil || o.Mssql == nil {
		return nil, false
	}
	return o.Mssql, true
}

// HasMssql returns a boolean if a field has been set.
func (o *SystemProfile) HasMssql() bool {
	if o != nil && o.Mssql != nil {
		return true
	}

	return false
}

// SetMssql gets a reference to the given SystemProfileMssql and assigns it to the Mssql field.
func (o *SystemProfile) SetMssql(v SystemProfileMssql) {
	o.Mssql = &v
}

// GetNetworkInterfaces returns the NetworkInterfaces field value if set, zero value otherwise.
func (o *SystemProfile) GetNetworkInterfaces() []SystemProfileNetworkInterface {
	if o == nil || o.NetworkInterfaces == nil {
		var ret []SystemProfileNetworkInterface
		return ret
	}
	return *o.NetworkInterfaces
}

// GetNetworkInterfacesOk returns a tuple with the NetworkInterfaces field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetNetworkInterfacesOk() (*[]SystemProfileNetworkInterface, bool) {
	if o == nil || o.NetworkInterfaces == nil {
		return nil, false
	}
	return o.NetworkInterfaces, true
}

// HasNetworkInterfaces returns a boolean if a field has been set.
func (o *SystemProfile) HasNetworkInterfaces() bool {
	if o != nil && o.NetworkInterfaces != nil {
		return true
	}

	return false
}

// SetNetworkInterfaces gets a reference to the given []SystemProfileNetworkInterface and assigns it to the NetworkInterfaces field.
func (o *SystemProfile) SetNetworkInterfaces(v []SystemProfileNetworkInterface) {
	o.NetworkInterfaces = &v
}

// GetNumberOfCpus returns the NumberOfCpus field value if set, zero value otherwise.
func (o *SystemProfile) GetNumberOfCpus() int32 {
	if o == nil || o.NumberOfCpus == nil {
		var ret int32
		return ret
	}
	return *o.NumberOfCpus
}

// GetNumberOfCpusOk returns a tuple with the NumberOfCpus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetNumberOfCpusOk() (*int32, bool) {
	if o == nil || o.NumberOfCpus == nil {
		return nil, false
	}
	return o.NumberOfCpus, true
}

// HasNumberOfCpus returns a boolean if a field has been set.
func (o *SystemProfile) HasNumberOfCpus() bool {
	if o != nil && o.NumberOfCpus != nil {
		return true
	}

	return false
}

// SetNumberOfCpus gets a reference to the given int32 and assigns it to the NumberOfCpus field.
func (o *SystemProfile) SetNumberOfCpus(v int32) {
	o.NumberOfCpus = &v
}

// GetNumberOfSockets returns the NumberOfSockets field value if set, zero value otherwise.
func (o *SystemProfile) GetNumberOfSockets() int32 {
	if o == nil || o.NumberOfSockets == nil {
		var ret int32
		return ret
	}
	return *o.NumberOfSockets
}

// GetNumberOfSocketsOk returns a tuple with the NumberOfSockets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetNumberOfSocketsOk() (*int32, bool) {
	if o == nil || o.NumberOfSockets == nil {
		return nil, false
	}
	return o.NumberOfSockets, true
}

// HasNumberOfSockets returns a boolean if a field has been set.
func (o *SystemProfile) HasNumberOfSockets() bool {
	if o != nil && o.NumberOfSockets != nil {
		return true
	}

	return false
}

// SetNumberOfSockets gets a reference to the given int32 and assigns it to the NumberOfSockets field.
func (o *SystemProfile) SetNumberOfSockets(v int32) {
	o.NumberOfSockets = &v
}

// GetOperatingSystem returns the OperatingSystem field value if set, zero value otherwise.
func (o *SystemProfile) GetOperatingSystem() SystemProfileOperatingSystem {
	if o == nil || o.OperatingSystem == nil {
		var ret SystemProfileOperatingSystem
		return ret
	}
	return *o.OperatingSystem
}

// GetOperatingSystemOk returns a tuple with the OperatingSystem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetOperatingSystemOk() (*SystemProfileOperatingSystem, bool) {
	if o == nil || o.OperatingSystem == nil {
		return nil, false
	}
	return o.OperatingSystem, true
}

// HasOperatingSystem returns a boolean if a field has been set.
func (o *SystemProfile) HasOperatingSystem() bool {
	if o != nil && o.OperatingSystem != nil {
		return true
	}

	return false
}

// SetOperatingSystem gets a reference to the given SystemProfileOperatingSystem and assigns it to the OperatingSystem field.
func (o *SystemProfile) SetOperatingSystem(v SystemProfileOperatingSystem) {
	o.OperatingSystem = &v
}

// GetOsKernelVersion returns the OsKernelVersion field value if set, zero value otherwise.
func (o *SystemProfile) GetOsKernelVersion() string {
	if o == nil || o.OsKernelVersion == nil {
		var ret string
		return ret
	}
	return *o.OsKernelVersion
}

// GetOsKernelVersionOk returns a tuple with the OsKernelVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetOsKernelVersionOk() (*string, bool) {
	if o == nil || o.OsKernelVersion == nil {
		return nil, false
	}
	return o.OsKernelVersion, true
}

// HasOsKernelVersion returns a boolean if a field has been set.
func (o *SystemProfile) HasOsKernelVersion() bool {
	if o != nil && o.OsKernelVersion != nil {
		return true
	}

	return false
}

// SetOsKernelVersion gets a reference to the given string and assigns it to the OsKernelVersion field.
func (o *SystemProfile) SetOsKernelVersion(v string) {
	o.OsKernelVersion = &v
}

// GetOsRelease returns the OsRelease field value if set, zero value otherwise.
func (o *SystemProfile) GetOsRelease() string {
	if o == nil || o.OsRelease == nil {
		var ret string
		return ret
	}
	return *o.OsRelease
}

// GetOsReleaseOk returns a tuple with the OsRelease field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetOsReleaseOk() (*string, bool) {
	if o == nil || o.OsRelease == nil {
		return nil, false
	}
	return o.OsRelease, true
}

// HasOsRelease returns a boolean if a field has been set.
func (o *SystemProfile) HasOsRelease() bool {
	if o != nil && o.OsRelease != nil {
		return true
	}

	return false
}

// SetOsRelease gets a reference to the given string and assigns it to the OsRelease field.
func (o *SystemProfile) SetOsRelease(v string) {
	o.OsRelease = &v
}

// GetOwnerId returns the OwnerId field value if set, zero value otherwise.
func (o *SystemProfile) GetOwnerId() string {
	if o == nil || o.OwnerId == nil {
		var ret string
		return ret
	}
	return *o.OwnerId
}

// GetOwnerIdOk returns a tuple with the OwnerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetOwnerIdOk() (*string, bool) {
	if o == nil || o.OwnerId == nil {
		return nil, false
	}
	return o.OwnerId, true
}

// HasOwnerId returns a boolean if a field has been set.
func (o *SystemProfile) HasOwnerId() bool {
	if o != nil && o.OwnerId != nil {
		return true
	}

	return false
}

// SetOwnerId gets a reference to the given string and assigns it to the OwnerId field.
func (o *SystemProfile) SetOwnerId(v string) {
	o.OwnerId = &v
}

// GetRhcClientId returns the RhcClientId field value if set, zero value otherwise.
func (o *SystemProfile) GetRhcClientId() string {
	if o == nil || o.RhcClientId == nil {
		var ret string
		return ret
	}
	return *o.RhcClientId
}

// GetRhcClientIdOk returns a tuple with the RhcClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetRhcClientIdOk() (*string, bool) {
	if o == nil || o.RhcClientId == nil {
		return nil, false
	}
	return o.RhcClientId, true
}

// HasRhcClientId returns a boolean if a field has been set.
func (o *SystemProfile) HasRhcClientId() bool {
	if o != nil && o.RhcClientId != nil {
		return true
	}

	return false
}

// SetRhcClientId gets a reference to the given string and assigns it to the RhcClientId field.
func (o *SystemProfile) SetRhcClientId(v string) {
	o.RhcClientId = &v
}

// GetRhcConfigState returns the RhcConfigState field value if set, zero value otherwise.
func (o *SystemProfile) GetRhcConfigState() string {
	if o == nil || o.RhcConfigState == nil {
		var ret string
		return ret
	}
	return *o.RhcConfigState
}

// GetRhcConfigStateOk returns a tuple with the RhcConfigState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetRhcConfigStateOk() (*string, bool) {
	if o == nil || o.RhcConfigState == nil {
		return nil, false
	}
	return o.RhcConfigState, true
}

// HasRhcConfigState returns a boolean if a field has been set.
func (o *SystemProfile) HasRhcConfigState() bool {
	if o != nil && o.RhcConfigState != nil {
		return true
	}

	return false
}

// SetRhcConfigState gets a reference to the given string and assigns it to the RhcConfigState field.
func (o *SystemProfile) SetRhcConfigState(v string) {
	o.RhcConfigState = &v
}

// GetRhsm returns the Rhsm field value if set, zero value otherwise.
func (o *SystemProfile) GetRhsm() SystemProfileRhsm {
	if o == nil || o.Rhsm == nil {
		var ret SystemProfileRhsm
		return ret
	}
	return *o.Rhsm
}

// GetRhsmOk returns a tuple with the Rhsm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetRhsmOk() (*SystemProfileRhsm, bool) {
	if o == nil || o.Rhsm == nil {
		return nil, false
	}
	return o.Rhsm, true
}

// HasRhsm returns a boolean if a field has been set.
func (o *SystemProfile) HasRhsm() bool {
	if o != nil && o.Rhsm != nil {
		return true
	}

	return false
}

// SetRhsm gets a reference to the given SystemProfileRhsm and assigns it to the Rhsm field.
func (o *SystemProfile) SetRhsm(v SystemProfileRhsm) {
	o.Rhsm = &v
}

// GetRpmOstreeDeployments returns the RpmOstreeDeployments field value if set, zero value otherwise.
func (o *SystemProfile) GetRpmOstreeDeployments() []SystemProfileRpmOstreeDeployments {
	if o == nil || o.RpmOstreeDeployments == nil {
		var ret []SystemProfileRpmOstreeDeployments
		return ret
	}
	return *o.RpmOstreeDeployments
}

// GetRpmOstreeDeploymentsOk returns a tuple with the RpmOstreeDeployments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetRpmOstreeDeploymentsOk() (*[]SystemProfileRpmOstreeDeployments, bool) {
	if o == nil || o.RpmOstreeDeployments == nil {
		return nil, false
	}
	return o.RpmOstreeDeployments, true
}

// HasRpmOstreeDeployments returns a boolean if a field has been set.
func (o *SystemProfile) HasRpmOstreeDeployments() bool {
	if o != nil && o.RpmOstreeDeployments != nil {
		return true
	}

	return false
}

// SetRpmOstreeDeployments gets a reference to the given []SystemProfileRpmOstreeDeployments and assigns it to the RpmOstreeDeployments field.
func (o *SystemProfile) SetRpmOstreeDeployments(v []SystemProfileRpmOstreeDeployments) {
	o.RpmOstreeDeployments = &v
}

// GetRunningProcesses returns the RunningProcesses field value if set, zero value otherwise.
func (o *SystemProfile) GetRunningProcesses() []string {
	if o == nil || o.RunningProcesses == nil {
		var ret []string
		return ret
	}
	return *o.RunningProcesses
}

// GetRunningProcessesOk returns a tuple with the RunningProcesses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetRunningProcessesOk() (*[]string, bool) {
	if o == nil || o.RunningProcesses == nil {
		return nil, false
	}
	return o.RunningProcesses, true
}

// HasRunningProcesses returns a boolean if a field has been set.
func (o *SystemProfile) HasRunningProcesses() bool {
	if o != nil && o.RunningProcesses != nil {
		return true
	}

	return false
}

// SetRunningProcesses gets a reference to the given []string and assigns it to the RunningProcesses field.
func (o *SystemProfile) SetRunningProcesses(v []string) {
	o.RunningProcesses = &v
}

// GetSapInstanceNumber returns the SapInstanceNumber field value if set, zero value otherwise.
func (o *SystemProfile) GetSapInstanceNumber() string {
	if o == nil || o.SapInstanceNumber == nil {
		var ret string
		return ret
	}
	return *o.SapInstanceNumber
}

// GetSapInstanceNumberOk returns a tuple with the SapInstanceNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetSapInstanceNumberOk() (*string, bool) {
	if o == nil || o.SapInstanceNumber == nil {
		return nil, false
	}
	return o.SapInstanceNumber, true
}

// HasSapInstanceNumber returns a boolean if a field has been set.
func (o *SystemProfile) HasSapInstanceNumber() bool {
	if o != nil && o.SapInstanceNumber != nil {
		return true
	}

	return false
}

// SetSapInstanceNumber gets a reference to the given string and assigns it to the SapInstanceNumber field.
func (o *SystemProfile) SetSapInstanceNumber(v string) {
	o.SapInstanceNumber = &v
}

// GetSapSids returns the SapSids field value if set, zero value otherwise.
func (o *SystemProfile) GetSapSids() []string {
	if o == nil || o.SapSids == nil {
		var ret []string
		return ret
	}
	return *o.SapSids
}

// GetSapSidsOk returns a tuple with the SapSids field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetSapSidsOk() (*[]string, bool) {
	if o == nil || o.SapSids == nil {
		return nil, false
	}
	return o.SapSids, true
}

// HasSapSids returns a boolean if a field has been set.
func (o *SystemProfile) HasSapSids() bool {
	if o != nil && o.SapSids != nil {
		return true
	}

	return false
}

// SetSapSids gets a reference to the given []string and assigns it to the SapSids field.
func (o *SystemProfile) SetSapSids(v []string) {
	o.SapSids = &v
}

// GetSapSystem returns the SapSystem field value if set, zero value otherwise.
func (o *SystemProfile) GetSapSystem() bool {
	if o == nil || o.SapSystem == nil {
		var ret bool
		return ret
	}
	return *o.SapSystem
}

// GetSapSystemOk returns a tuple with the SapSystem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetSapSystemOk() (*bool, bool) {
	if o == nil || o.SapSystem == nil {
		return nil, false
	}
	return o.SapSystem, true
}

// HasSapSystem returns a boolean if a field has been set.
func (o *SystemProfile) HasSapSystem() bool {
	if o != nil && o.SapSystem != nil {
		return true
	}

	return false
}

// SetSapSystem gets a reference to the given bool and assigns it to the SapSystem field.
func (o *SystemProfile) SetSapSystem(v bool) {
	o.SapSystem = &v
}

// GetSapVersion returns the SapVersion field value if set, zero value otherwise.
func (o *SystemProfile) GetSapVersion() string {
	if o == nil || o.SapVersion == nil {
		var ret string
		return ret
	}
	return *o.SapVersion
}

// GetSapVersionOk returns a tuple with the SapVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetSapVersionOk() (*string, bool) {
	if o == nil || o.SapVersion == nil {
		return nil, false
	}
	return o.SapVersion, true
}

// HasSapVersion returns a boolean if a field has been set.
func (o *SystemProfile) HasSapVersion() bool {
	if o != nil && o.SapVersion != nil {
		return true
	}

	return false
}

// SetSapVersion gets a reference to the given string and assigns it to the SapVersion field.
func (o *SystemProfile) SetSapVersion(v string) {
	o.SapVersion = &v
}

// GetSatelliteManaged returns the SatelliteManaged field value if set, zero value otherwise.
func (o *SystemProfile) GetSatelliteManaged() bool {
	if o == nil || o.SatelliteManaged == nil {
		var ret bool
		return ret
	}
	return *o.SatelliteManaged
}

// GetSatelliteManagedOk returns a tuple with the SatelliteManaged field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetSatelliteManagedOk() (*bool, bool) {
	if o == nil || o.SatelliteManaged == nil {
		return nil, false
	}
	return o.SatelliteManaged, true
}

// HasSatelliteManaged returns a boolean if a field has been set.
func (o *SystemProfile) HasSatelliteManaged() bool {
	if o != nil && o.SatelliteManaged != nil {
		return true
	}

	return false
}

// SetSatelliteManaged gets a reference to the given bool and assigns it to the SatelliteManaged field.
func (o *SystemProfile) SetSatelliteManaged(v bool) {
	o.SatelliteManaged = &v
}

// GetSelinuxConfigFile returns the SelinuxConfigFile field value if set, zero value otherwise.
func (o *SystemProfile) GetSelinuxConfigFile() string {
	if o == nil || o.SelinuxConfigFile == nil {
		var ret string
		return ret
	}
	return *o.SelinuxConfigFile
}

// GetSelinuxConfigFileOk returns a tuple with the SelinuxConfigFile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetSelinuxConfigFileOk() (*string, bool) {
	if o == nil || o.SelinuxConfigFile == nil {
		return nil, false
	}
	return o.SelinuxConfigFile, true
}

// HasSelinuxConfigFile returns a boolean if a field has been set.
func (o *SystemProfile) HasSelinuxConfigFile() bool {
	if o != nil && o.SelinuxConfigFile != nil {
		return true
	}

	return false
}

// SetSelinuxConfigFile gets a reference to the given string and assigns it to the SelinuxConfigFile field.
func (o *SystemProfile) SetSelinuxConfigFile(v string) {
	o.SelinuxConfigFile = &v
}

// GetSelinuxCurrentMode returns the SelinuxCurrentMode field value if set, zero value otherwise.
func (o *SystemProfile) GetSelinuxCurrentMode() string {
	if o == nil || o.SelinuxCurrentMode == nil {
		var ret string
		return ret
	}
	return *o.SelinuxCurrentMode
}

// GetSelinuxCurrentModeOk returns a tuple with the SelinuxCurrentMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetSelinuxCurrentModeOk() (*string, bool) {
	if o == nil || o.SelinuxCurrentMode == nil {
		return nil, false
	}
	return o.SelinuxCurrentMode, true
}

// HasSelinuxCurrentMode returns a boolean if a field has been set.
func (o *SystemProfile) HasSelinuxCurrentMode() bool {
	if o != nil && o.SelinuxCurrentMode != nil {
		return true
	}

	return false
}

// SetSelinuxCurrentMode gets a reference to the given string and assigns it to the SelinuxCurrentMode field.
func (o *SystemProfile) SetSelinuxCurrentMode(v string) {
	o.SelinuxCurrentMode = &v
}

// GetSubscriptionAutoAttach returns the SubscriptionAutoAttach field value if set, zero value otherwise.
func (o *SystemProfile) GetSubscriptionAutoAttach() string {
	if o == nil || o.SubscriptionAutoAttach == nil {
		var ret string
		return ret
	}
	return *o.SubscriptionAutoAttach
}

// GetSubscriptionAutoAttachOk returns a tuple with the SubscriptionAutoAttach field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetSubscriptionAutoAttachOk() (*string, bool) {
	if o == nil || o.SubscriptionAutoAttach == nil {
		return nil, false
	}
	return o.SubscriptionAutoAttach, true
}

// HasSubscriptionAutoAttach returns a boolean if a field has been set.
func (o *SystemProfile) HasSubscriptionAutoAttach() bool {
	if o != nil && o.SubscriptionAutoAttach != nil {
		return true
	}

	return false
}

// SetSubscriptionAutoAttach gets a reference to the given string and assigns it to the SubscriptionAutoAttach field.
func (o *SystemProfile) SetSubscriptionAutoAttach(v string) {
	o.SubscriptionAutoAttach = &v
}

// GetSubscriptionStatus returns the SubscriptionStatus field value if set, zero value otherwise.
func (o *SystemProfile) GetSubscriptionStatus() string {
	if o == nil || o.SubscriptionStatus == nil {
		var ret string
		return ret
	}
	return *o.SubscriptionStatus
}

// GetSubscriptionStatusOk returns a tuple with the SubscriptionStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetSubscriptionStatusOk() (*string, bool) {
	if o == nil || o.SubscriptionStatus == nil {
		return nil, false
	}
	return o.SubscriptionStatus, true
}

// HasSubscriptionStatus returns a boolean if a field has been set.
func (o *SystemProfile) HasSubscriptionStatus() bool {
	if o != nil && o.SubscriptionStatus != nil {
		return true
	}

	return false
}

// SetSubscriptionStatus gets a reference to the given string and assigns it to the SubscriptionStatus field.
func (o *SystemProfile) SetSubscriptionStatus(v string) {
	o.SubscriptionStatus = &v
}

// GetSystemMemoryBytes returns the SystemMemoryBytes field value if set, zero value otherwise.
func (o *SystemProfile) GetSystemMemoryBytes() int64 {
	if o == nil || o.SystemMemoryBytes == nil {
		var ret int64
		return ret
	}
	return *o.SystemMemoryBytes
}

// GetSystemMemoryBytesOk returns a tuple with the SystemMemoryBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetSystemMemoryBytesOk() (*int64, bool) {
	if o == nil || o.SystemMemoryBytes == nil {
		return nil, false
	}
	return o.SystemMemoryBytes, true
}

// HasSystemMemoryBytes returns a boolean if a field has been set.
func (o *SystemProfile) HasSystemMemoryBytes() bool {
	if o != nil && o.SystemMemoryBytes != nil {
		return true
	}

	return false
}

// SetSystemMemoryBytes gets a reference to the given int64 and assigns it to the SystemMemoryBytes field.
func (o *SystemProfile) SetSystemMemoryBytes(v int64) {
	o.SystemMemoryBytes = &v
}

// GetSystemPurpose returns the SystemPurpose field value if set, zero value otherwise.
func (o *SystemProfile) GetSystemPurpose() SystemProfileSystemPurpose {
	if o == nil || o.SystemPurpose == nil {
		var ret SystemProfileSystemPurpose
		return ret
	}
	return *o.SystemPurpose
}

// GetSystemPurposeOk returns a tuple with the SystemPurpose field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetSystemPurposeOk() (*SystemProfileSystemPurpose, bool) {
	if o == nil || o.SystemPurpose == nil {
		return nil, false
	}
	return o.SystemPurpose, true
}

// HasSystemPurpose returns a boolean if a field has been set.
func (o *SystemProfile) HasSystemPurpose() bool {
	if o != nil && o.SystemPurpose != nil {
		return true
	}

	return false
}

// SetSystemPurpose gets a reference to the given SystemProfileSystemPurpose and assigns it to the SystemPurpose field.
func (o *SystemProfile) SetSystemPurpose(v SystemProfileSystemPurpose) {
	o.SystemPurpose = &v
}

// GetTunedProfile returns the TunedProfile field value if set, zero value otherwise.
func (o *SystemProfile) GetTunedProfile() string {
	if o == nil || o.TunedProfile == nil {
		var ret string
		return ret
	}
	return *o.TunedProfile
}

// GetTunedProfileOk returns a tuple with the TunedProfile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetTunedProfileOk() (*string, bool) {
	if o == nil || o.TunedProfile == nil {
		return nil, false
	}
	return o.TunedProfile, true
}

// HasTunedProfile returns a boolean if a field has been set.
func (o *SystemProfile) HasTunedProfile() bool {
	if o != nil && o.TunedProfile != nil {
		return true
	}

	return false
}

// SetTunedProfile gets a reference to the given string and assigns it to the TunedProfile field.
func (o *SystemProfile) SetTunedProfile(v string) {
	o.TunedProfile = &v
}

// GetYumRepos returns the YumRepos field value if set, zero value otherwise.
func (o *SystemProfile) GetYumRepos() []SystemProfileYumRepo {
	if o == nil || o.YumRepos == nil {
		var ret []SystemProfileYumRepo
		return ret
	}
	return *o.YumRepos
}

// GetYumReposOk returns a tuple with the YumRepos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetYumReposOk() (*[]SystemProfileYumRepo, bool) {
	if o == nil || o.YumRepos == nil {
		return nil, false
	}
	return o.YumRepos, true
}

// HasYumRepos returns a boolean if a field has been set.
func (o *SystemProfile) HasYumRepos() bool {
	if o != nil && o.YumRepos != nil {
		return true
	}

	return false
}

// SetYumRepos gets a reference to the given []SystemProfileYumRepo and assigns it to the YumRepos field.
func (o *SystemProfile) SetYumRepos(v []SystemProfileYumRepo) {
	o.YumRepos = &v
}

func (o SystemProfile) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Ansible != nil {
		toSerialize["ansible"] = o.Ansible
	}
	if o.Arch != nil {
		toSerialize["arch"] = o.Arch
	}
	if o.BiosReleaseDate != nil {
		toSerialize["bios_release_date"] = o.BiosReleaseDate
	}
	if o.BiosVendor != nil {
		toSerialize["bios_vendor"] = o.BiosVendor
	}
	if o.BiosVersion != nil {
		toSerialize["bios_version"] = o.BiosVersion
	}
	if o.CapturedDate != nil {
		toSerialize["captured_date"] = o.CapturedDate
	}
	if o.CloudProvider != nil {
		toSerialize["cloud_provider"] = o.CloudProvider
	}
	if o.CoresPerSocket != nil {
		toSerialize["cores_per_socket"] = o.CoresPerSocket
	}
	if o.CpuFlags != nil {
		toSerialize["cpu_flags"] = o.CpuFlags
	}
	if o.CpuModel != nil {
		toSerialize["cpu_model"] = o.CpuModel
	}
	if o.DiskDevices != nil {
		toSerialize["disk_devices"] = o.DiskDevices
	}
	if o.DnfModules != nil {
		toSerialize["dnf_modules"] = o.DnfModules
	}
	if o.EnabledServices != nil {
		toSerialize["enabled_services"] = o.EnabledServices
	}
	if o.GpgPubkeys != nil {
		toSerialize["gpg_pubkeys"] = o.GpgPubkeys
	}
	if o.GreenbootFallbackDetected != nil {
		toSerialize["greenboot_fallback_detected"] = o.GreenbootFallbackDetected
	}
	if o.GreenbootStatus != nil {
		toSerialize["greenboot_status"] = o.GreenbootStatus
	}
	if o.HostType != nil {
		toSerialize["host_type"] = o.HostType
	}
	if o.InfrastructureType != nil {
		toSerialize["infrastructure_type"] = o.InfrastructureType
	}
	if o.InfrastructureVendor != nil {
		toSerialize["infrastructure_vendor"] = o.InfrastructureVendor
	}
	if o.InsightsClientVersion != nil {
		toSerialize["insights_client_version"] = o.InsightsClientVersion
	}
	if o.InsightsEggVersion != nil {
		toSerialize["insights_egg_version"] = o.InsightsEggVersion
	}
	if o.InstalledPackages != nil {
		toSerialize["installed_packages"] = o.InstalledPackages
	}
	if o.InstalledPackagesDelta != nil {
		toSerialize["installed_packages_delta"] = o.InstalledPackagesDelta
	}
	if o.InstalledProducts != nil {
		toSerialize["installed_products"] = o.InstalledProducts
	}
	if o.InstalledServices != nil {
		toSerialize["installed_services"] = o.InstalledServices
	}
	if o.IsMarketplace != nil {
		toSerialize["is_marketplace"] = o.IsMarketplace
	}
	if o.KatelloAgentRunning != nil {
		toSerialize["katello_agent_running"] = o.KatelloAgentRunning
	}
	if o.KernelModules != nil {
		toSerialize["kernel_modules"] = o.KernelModules
	}
	if o.LastBootTime != nil {
		toSerialize["last_boot_time"] = o.LastBootTime
	}
	if o.Mssql != nil {
		toSerialize["mssql"] = o.Mssql
	}
	if o.NetworkInterfaces != nil {
		toSerialize["network_interfaces"] = o.NetworkInterfaces
	}
	if o.NumberOfCpus != nil {
		toSerialize["number_of_cpus"] = o.NumberOfCpus
	}
	if o.NumberOfSockets != nil {
		toSerialize["number_of_sockets"] = o.NumberOfSockets
	}
	if o.OperatingSystem != nil {
		toSerialize["operating_system"] = o.OperatingSystem
	}
	if o.OsKernelVersion != nil {
		toSerialize["os_kernel_version"] = o.OsKernelVersion
	}
	if o.OsRelease != nil {
		toSerialize["os_release"] = o.OsRelease
	}
	if o.OwnerId != nil {
		toSerialize["owner_id"] = o.OwnerId
	}
	if o.RhcClientId != nil {
		toSerialize["rhc_client_id"] = o.RhcClientId
	}
	if o.RhcConfigState != nil {
		toSerialize["rhc_config_state"] = o.RhcConfigState
	}
	if o.Rhsm != nil {
		toSerialize["rhsm"] = o.Rhsm
	}
	if o.RpmOstreeDeployments != nil {
		toSerialize["rpm_ostree_deployments"] = o.RpmOstreeDeployments
	}
	if o.RunningProcesses != nil {
		toSerialize["running_processes"] = o.RunningProcesses
	}
	if o.SapInstanceNumber != nil {
		toSerialize["sap_instance_number"] = o.SapInstanceNumber
	}
	if o.SapSids != nil {
		toSerialize["sap_sids"] = o.SapSids
	}
	if o.SapSystem != nil {
		toSerialize["sap_system"] = o.SapSystem
	}
	if o.SapVersion != nil {
		toSerialize["sap_version"] = o.SapVersion
	}
	if o.SatelliteManaged != nil {
		toSerialize["satellite_managed"] = o.SatelliteManaged
	}
	if o.SelinuxConfigFile != nil {
		toSerialize["selinux_config_file"] = o.SelinuxConfigFile
	}
	if o.SelinuxCurrentMode != nil {
		toSerialize["selinux_current_mode"] = o.SelinuxCurrentMode
	}
	if o.SubscriptionAutoAttach != nil {
		toSerialize["subscription_auto_attach"] = o.SubscriptionAutoAttach
	}
	if o.SubscriptionStatus != nil {
		toSerialize["subscription_status"] = o.SubscriptionStatus
	}
	if o.SystemMemoryBytes != nil {
		toSerialize["system_memory_bytes"] = o.SystemMemoryBytes
	}
	if o.SystemPurpose != nil {
		toSerialize["system_purpose"] = o.SystemPurpose
	}
	if o.TunedProfile != nil {
		toSerialize["tuned_profile"] = o.TunedProfile
	}
	if o.YumRepos != nil {
		toSerialize["yum_repos"] = o.YumRepos
	}
	return json.Marshal(toSerialize)
}

type NullableSystemProfile struct {
	value *SystemProfile
	isSet bool
}

func (v NullableSystemProfile) Get() *SystemProfile {
	return v.value
}

func (v *NullableSystemProfile) Set(val *SystemProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemProfile(val *SystemProfile) *NullableSystemProfile {
	return &NullableSystemProfile{value: val, isSet: true}
}

func (v NullableSystemProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


