/*
 * Insights Host Inventory REST Interface
 *
 * REST interface for the Insights Platform Host Inventory application.
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package inventory

import (
	"encoding/json"
)

// SystemProfileNetworkInterface Representation of one network interface
type SystemProfileNetworkInterface struct {
	Ipv4Addresses *[]string `json:"ipv4_addresses,omitempty"`
	Ipv6Addresses *[]string `json:"ipv6_addresses,omitempty"`
	// MAC address (with or without colons)
	MacAddress *string `json:"mac_address,omitempty"`
	// MTU (Maximum transmission unit)
	Mtu *int32 `json:"mtu,omitempty"`
	// Name of interface
	Name *string `json:"name,omitempty"`
	// Interface state (UP, DOWN, UNKNOWN)
	State *string `json:"state,omitempty"`
	// Interface type (ether, loopback)
	Type *string `json:"type,omitempty"`
}

// NewSystemProfileNetworkInterface instantiates a new SystemProfileNetworkInterface object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemProfileNetworkInterface() *SystemProfileNetworkInterface {
	this := SystemProfileNetworkInterface{}
	return &this
}

// NewSystemProfileNetworkInterfaceWithDefaults instantiates a new SystemProfileNetworkInterface object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemProfileNetworkInterfaceWithDefaults() *SystemProfileNetworkInterface {
	this := SystemProfileNetworkInterface{}
	return &this
}

// GetIpv4Addresses returns the Ipv4Addresses field value if set, zero value otherwise.
func (o *SystemProfileNetworkInterface) GetIpv4Addresses() []string {
	if o == nil || o.Ipv4Addresses == nil {
		var ret []string
		return ret
	}
	return *o.Ipv4Addresses
}

// GetIpv4AddressesOk returns a tuple with the Ipv4Addresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfileNetworkInterface) GetIpv4AddressesOk() (*[]string, bool) {
	if o == nil || o.Ipv4Addresses == nil {
		return nil, false
	}
	return o.Ipv4Addresses, true
}

// HasIpv4Addresses returns a boolean if a field has been set.
func (o *SystemProfileNetworkInterface) HasIpv4Addresses() bool {
	if o != nil && o.Ipv4Addresses != nil {
		return true
	}

	return false
}

// SetIpv4Addresses gets a reference to the given []string and assigns it to the Ipv4Addresses field.
func (o *SystemProfileNetworkInterface) SetIpv4Addresses(v []string) {
	o.Ipv4Addresses = &v
}

// GetIpv6Addresses returns the Ipv6Addresses field value if set, zero value otherwise.
func (o *SystemProfileNetworkInterface) GetIpv6Addresses() []string {
	if o == nil || o.Ipv6Addresses == nil {
		var ret []string
		return ret
	}
	return *o.Ipv6Addresses
}

// GetIpv6AddressesOk returns a tuple with the Ipv6Addresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfileNetworkInterface) GetIpv6AddressesOk() (*[]string, bool) {
	if o == nil || o.Ipv6Addresses == nil {
		return nil, false
	}
	return o.Ipv6Addresses, true
}

// HasIpv6Addresses returns a boolean if a field has been set.
func (o *SystemProfileNetworkInterface) HasIpv6Addresses() bool {
	if o != nil && o.Ipv6Addresses != nil {
		return true
	}

	return false
}

// SetIpv6Addresses gets a reference to the given []string and assigns it to the Ipv6Addresses field.
func (o *SystemProfileNetworkInterface) SetIpv6Addresses(v []string) {
	o.Ipv6Addresses = &v
}

// GetMacAddress returns the MacAddress field value if set, zero value otherwise.
func (o *SystemProfileNetworkInterface) GetMacAddress() string {
	if o == nil || o.MacAddress == nil {
		var ret string
		return ret
	}
	return *o.MacAddress
}

// GetMacAddressOk returns a tuple with the MacAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfileNetworkInterface) GetMacAddressOk() (*string, bool) {
	if o == nil || o.MacAddress == nil {
		return nil, false
	}
	return o.MacAddress, true
}

// HasMacAddress returns a boolean if a field has been set.
func (o *SystemProfileNetworkInterface) HasMacAddress() bool {
	if o != nil && o.MacAddress != nil {
		return true
	}

	return false
}

// SetMacAddress gets a reference to the given string and assigns it to the MacAddress field.
func (o *SystemProfileNetworkInterface) SetMacAddress(v string) {
	o.MacAddress = &v
}

// GetMtu returns the Mtu field value if set, zero value otherwise.
func (o *SystemProfileNetworkInterface) GetMtu() int32 {
	if o == nil || o.Mtu == nil {
		var ret int32
		return ret
	}
	return *o.Mtu
}

// GetMtuOk returns a tuple with the Mtu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfileNetworkInterface) GetMtuOk() (*int32, bool) {
	if o == nil || o.Mtu == nil {
		return nil, false
	}
	return o.Mtu, true
}

// HasMtu returns a boolean if a field has been set.
func (o *SystemProfileNetworkInterface) HasMtu() bool {
	if o != nil && o.Mtu != nil {
		return true
	}

	return false
}

// SetMtu gets a reference to the given int32 and assigns it to the Mtu field.
func (o *SystemProfileNetworkInterface) SetMtu(v int32) {
	o.Mtu = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SystemProfileNetworkInterface) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfileNetworkInterface) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SystemProfileNetworkInterface) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SystemProfileNetworkInterface) SetName(v string) {
	o.Name = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *SystemProfileNetworkInterface) GetState() string {
	if o == nil || o.State == nil {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfileNetworkInterface) GetStateOk() (*string, bool) {
	if o == nil || o.State == nil {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *SystemProfileNetworkInterface) HasState() bool {
	if o != nil && o.State != nil {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *SystemProfileNetworkInterface) SetState(v string) {
	o.State = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *SystemProfileNetworkInterface) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfileNetworkInterface) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *SystemProfileNetworkInterface) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *SystemProfileNetworkInterface) SetType(v string) {
	o.Type = &v
}

func (o SystemProfileNetworkInterface) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Ipv4Addresses != nil {
		toSerialize["ipv4_addresses"] = o.Ipv4Addresses
	}
	if o.Ipv6Addresses != nil {
		toSerialize["ipv6_addresses"] = o.Ipv6Addresses
	}
	if o.MacAddress != nil {
		toSerialize["mac_address"] = o.MacAddress
	}
	if o.Mtu != nil {
		toSerialize["mtu"] = o.Mtu
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.State != nil {
		toSerialize["state"] = o.State
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableSystemProfileNetworkInterface struct {
	value *SystemProfileNetworkInterface
	isSet bool
}

func (v NullableSystemProfileNetworkInterface) Get() *SystemProfileNetworkInterface {
	return v.value
}

func (v *NullableSystemProfileNetworkInterface) Set(val *SystemProfileNetworkInterface) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemProfileNetworkInterface) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemProfileNetworkInterface) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemProfileNetworkInterface(val *SystemProfileNetworkInterface) *NullableSystemProfileNetworkInterface {
	return &NullableSystemProfileNetworkInterface{value: val, isSet: true}
}

func (v NullableSystemProfileNetworkInterface) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemProfileNetworkInterface) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


