/*
 * Insights Host Inventory REST Interface
 *
 * REST interface for the Insights Platform Host Inventory application.
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package inventory

import (
	"encoding/json"
)

// CreateHostIn Data of a single host belonging to an account. Represents the hosts without its Inventory metadata.
type CreateHostIn struct {
	// A Red Hat Account number that owns the host.
	Account string `json:"account"`
	// The ansible host name for remediations
	AnsibleHost *string `json:"ansible_host,omitempty"`
	// A UUID of the host machine BIOS.  This field is considered to be a canonical fact.
	BiosUuid *string `json:"bios_uuid,omitempty"`
	// A host’s human-readable display name, e.g. in a form of a domain name.
	DisplayName *string `json:"display_name,omitempty"`
	// Host’s reference in the external source e.g. AWS EC2, Azure, OpenStack, etc. This field is considered to be a canonical fact.
	ExternalId *string `json:"external_id,omitempty"`
	// A set of facts belonging to the host.
	Facts *[]FactSet `json:"facts,omitempty"`
	// A host’s Fully Qualified Domain Name.  This field is considered to be a canonical fact.
	Fqdn *string `json:"fqdn,omitempty"`
	// An ID defined in /etc/insights-client/machine-id. This field is considered a canonical fact.
	InsightsId *string `json:"insights_id,omitempty"`
	// Host’s network IP addresses.  This field is considered to be a canonical fact.
	IpAddresses *[]string `json:"ip_addresses,omitempty"`
	// Host’s network interfaces MAC addresses.  This field is considered to be a canonical fact.
	MacAddresses *[]string `json:"mac_addresses,omitempty"`
	// Reporting source of the host. Used when updating the stale_timestamp.
	Reporter string `json:"reporter"`
	// A Machine ID of a RHEL host.  This field is considered to be a canonical fact.
	RhelMachineId *string `json:"rhel_machine_id,omitempty"`
	// A Red Hat Satellite ID of a RHEL host.  This field is considered to be a canonical fact.
	SatelliteId *string `json:"satellite_id,omitempty"`
	// Timestamp from which the host is considered stale.
	StaleTimestamp string `json:"stale_timestamp"`
	// A Red Hat Subcription Manager ID of a RHEL host.  This field is considered to be a canonical fact.
	SubscriptionManagerId *string `json:"subscription_manager_id,omitempty"`
	SystemProfile *SystemProfile `json:"system_profile,omitempty"`
}

// NewCreateHostIn instantiates a new CreateHostIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateHostIn(account string, reporter string, staleTimestamp string, ) *CreateHostIn {
	this := CreateHostIn{}
	this.Account = account
	this.Reporter = reporter
	this.StaleTimestamp = staleTimestamp
	return &this
}

// NewCreateHostInWithDefaults instantiates a new CreateHostIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateHostInWithDefaults() *CreateHostIn {
	this := CreateHostIn{}
	return &this
}

// GetAccount returns the Account field value
func (o *CreateHostIn) GetAccount() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Account
}

// GetAccountOk returns a tuple with the Account field value
// and a boolean to check if the value has been set.
func (o *CreateHostIn) GetAccountOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Account, true
}

// SetAccount sets field value
func (o *CreateHostIn) SetAccount(v string) {
	o.Account = v
}

// GetAnsibleHost returns the AnsibleHost field value if set, zero value otherwise.
func (o *CreateHostIn) GetAnsibleHost() string {
	if o == nil || o.AnsibleHost == nil {
		var ret string
		return ret
	}
	return *o.AnsibleHost
}

// GetAnsibleHostOk returns a tuple with the AnsibleHost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateHostIn) GetAnsibleHostOk() (*string, bool) {
	if o == nil || o.AnsibleHost == nil {
		return nil, false
	}
	return o.AnsibleHost, true
}

// HasAnsibleHost returns a boolean if a field has been set.
func (o *CreateHostIn) HasAnsibleHost() bool {
	if o != nil && o.AnsibleHost != nil {
		return true
	}

	return false
}

// SetAnsibleHost gets a reference to the given string and assigns it to the AnsibleHost field.
func (o *CreateHostIn) SetAnsibleHost(v string) {
	o.AnsibleHost = &v
}

// GetBiosUuid returns the BiosUuid field value if set, zero value otherwise.
func (o *CreateHostIn) GetBiosUuid() string {
	if o == nil || o.BiosUuid == nil {
		var ret string
		return ret
	}
	return *o.BiosUuid
}

// GetBiosUuidOk returns a tuple with the BiosUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateHostIn) GetBiosUuidOk() (*string, bool) {
	if o == nil || o.BiosUuid == nil {
		return nil, false
	}
	return o.BiosUuid, true
}

// HasBiosUuid returns a boolean if a field has been set.
func (o *CreateHostIn) HasBiosUuid() bool {
	if o != nil && o.BiosUuid != nil {
		return true
	}

	return false
}

// SetBiosUuid gets a reference to the given string and assigns it to the BiosUuid field.
func (o *CreateHostIn) SetBiosUuid(v string) {
	o.BiosUuid = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *CreateHostIn) GetDisplayName() string {
	if o == nil || o.DisplayName == nil {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateHostIn) GetDisplayNameOk() (*string, bool) {
	if o == nil || o.DisplayName == nil {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *CreateHostIn) HasDisplayName() bool {
	if o != nil && o.DisplayName != nil {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *CreateHostIn) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *CreateHostIn) GetExternalId() string {
	if o == nil || o.ExternalId == nil {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateHostIn) GetExternalIdOk() (*string, bool) {
	if o == nil || o.ExternalId == nil {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *CreateHostIn) HasExternalId() bool {
	if o != nil && o.ExternalId != nil {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *CreateHostIn) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetFacts returns the Facts field value if set, zero value otherwise.
func (o *CreateHostIn) GetFacts() []FactSet {
	if o == nil || o.Facts == nil {
		var ret []FactSet
		return ret
	}
	return *o.Facts
}

// GetFactsOk returns a tuple with the Facts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateHostIn) GetFactsOk() (*[]FactSet, bool) {
	if o == nil || o.Facts == nil {
		return nil, false
	}
	return o.Facts, true
}

// HasFacts returns a boolean if a field has been set.
func (o *CreateHostIn) HasFacts() bool {
	if o != nil && o.Facts != nil {
		return true
	}

	return false
}

// SetFacts gets a reference to the given []FactSet and assigns it to the Facts field.
func (o *CreateHostIn) SetFacts(v []FactSet) {
	o.Facts = &v
}

// GetFqdn returns the Fqdn field value if set, zero value otherwise.
func (o *CreateHostIn) GetFqdn() string {
	if o == nil || o.Fqdn == nil {
		var ret string
		return ret
	}
	return *o.Fqdn
}

// GetFqdnOk returns a tuple with the Fqdn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateHostIn) GetFqdnOk() (*string, bool) {
	if o == nil || o.Fqdn == nil {
		return nil, false
	}
	return o.Fqdn, true
}

// HasFqdn returns a boolean if a field has been set.
func (o *CreateHostIn) HasFqdn() bool {
	if o != nil && o.Fqdn != nil {
		return true
	}

	return false
}

// SetFqdn gets a reference to the given string and assigns it to the Fqdn field.
func (o *CreateHostIn) SetFqdn(v string) {
	o.Fqdn = &v
}

// GetInsightsId returns the InsightsId field value if set, zero value otherwise.
func (o *CreateHostIn) GetInsightsId() string {
	if o == nil || o.InsightsId == nil {
		var ret string
		return ret
	}
	return *o.InsightsId
}

// GetInsightsIdOk returns a tuple with the InsightsId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateHostIn) GetInsightsIdOk() (*string, bool) {
	if o == nil || o.InsightsId == nil {
		return nil, false
	}
	return o.InsightsId, true
}

// HasInsightsId returns a boolean if a field has been set.
func (o *CreateHostIn) HasInsightsId() bool {
	if o != nil && o.InsightsId != nil {
		return true
	}

	return false
}

// SetInsightsId gets a reference to the given string and assigns it to the InsightsId field.
func (o *CreateHostIn) SetInsightsId(v string) {
	o.InsightsId = &v
}

// GetIpAddresses returns the IpAddresses field value if set, zero value otherwise.
func (o *CreateHostIn) GetIpAddresses() []string {
	if o == nil || o.IpAddresses == nil {
		var ret []string
		return ret
	}
	return *o.IpAddresses
}

// GetIpAddressesOk returns a tuple with the IpAddresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateHostIn) GetIpAddressesOk() (*[]string, bool) {
	if o == nil || o.IpAddresses == nil {
		return nil, false
	}
	return o.IpAddresses, true
}

// HasIpAddresses returns a boolean if a field has been set.
func (o *CreateHostIn) HasIpAddresses() bool {
	if o != nil && o.IpAddresses != nil {
		return true
	}

	return false
}

// SetIpAddresses gets a reference to the given []string and assigns it to the IpAddresses field.
func (o *CreateHostIn) SetIpAddresses(v []string) {
	o.IpAddresses = &v
}

// GetMacAddresses returns the MacAddresses field value if set, zero value otherwise.
func (o *CreateHostIn) GetMacAddresses() []string {
	if o == nil || o.MacAddresses == nil {
		var ret []string
		return ret
	}
	return *o.MacAddresses
}

// GetMacAddressesOk returns a tuple with the MacAddresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateHostIn) GetMacAddressesOk() (*[]string, bool) {
	if o == nil || o.MacAddresses == nil {
		return nil, false
	}
	return o.MacAddresses, true
}

// HasMacAddresses returns a boolean if a field has been set.
func (o *CreateHostIn) HasMacAddresses() bool {
	if o != nil && o.MacAddresses != nil {
		return true
	}

	return false
}

// SetMacAddresses gets a reference to the given []string and assigns it to the MacAddresses field.
func (o *CreateHostIn) SetMacAddresses(v []string) {
	o.MacAddresses = &v
}

// GetReporter returns the Reporter field value
func (o *CreateHostIn) GetReporter() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Reporter
}

// GetReporterOk returns a tuple with the Reporter field value
// and a boolean to check if the value has been set.
func (o *CreateHostIn) GetReporterOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Reporter, true
}

// SetReporter sets field value
func (o *CreateHostIn) SetReporter(v string) {
	o.Reporter = v
}

// GetRhelMachineId returns the RhelMachineId field value if set, zero value otherwise.
func (o *CreateHostIn) GetRhelMachineId() string {
	if o == nil || o.RhelMachineId == nil {
		var ret string
		return ret
	}
	return *o.RhelMachineId
}

// GetRhelMachineIdOk returns a tuple with the RhelMachineId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateHostIn) GetRhelMachineIdOk() (*string, bool) {
	if o == nil || o.RhelMachineId == nil {
		return nil, false
	}
	return o.RhelMachineId, true
}

// HasRhelMachineId returns a boolean if a field has been set.
func (o *CreateHostIn) HasRhelMachineId() bool {
	if o != nil && o.RhelMachineId != nil {
		return true
	}

	return false
}

// SetRhelMachineId gets a reference to the given string and assigns it to the RhelMachineId field.
func (o *CreateHostIn) SetRhelMachineId(v string) {
	o.RhelMachineId = &v
}

// GetSatelliteId returns the SatelliteId field value if set, zero value otherwise.
func (o *CreateHostIn) GetSatelliteId() string {
	if o == nil || o.SatelliteId == nil {
		var ret string
		return ret
	}
	return *o.SatelliteId
}

// GetSatelliteIdOk returns a tuple with the SatelliteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateHostIn) GetSatelliteIdOk() (*string, bool) {
	if o == nil || o.SatelliteId == nil {
		return nil, false
	}
	return o.SatelliteId, true
}

// HasSatelliteId returns a boolean if a field has been set.
func (o *CreateHostIn) HasSatelliteId() bool {
	if o != nil && o.SatelliteId != nil {
		return true
	}

	return false
}

// SetSatelliteId gets a reference to the given string and assigns it to the SatelliteId field.
func (o *CreateHostIn) SetSatelliteId(v string) {
	o.SatelliteId = &v
}

// GetStaleTimestamp returns the StaleTimestamp field value
func (o *CreateHostIn) GetStaleTimestamp() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.StaleTimestamp
}

// GetStaleTimestampOk returns a tuple with the StaleTimestamp field value
// and a boolean to check if the value has been set.
func (o *CreateHostIn) GetStaleTimestampOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.StaleTimestamp, true
}

// SetStaleTimestamp sets field value
func (o *CreateHostIn) SetStaleTimestamp(v string) {
	o.StaleTimestamp = v
}

// GetSubscriptionManagerId returns the SubscriptionManagerId field value if set, zero value otherwise.
func (o *CreateHostIn) GetSubscriptionManagerId() string {
	if o == nil || o.SubscriptionManagerId == nil {
		var ret string
		return ret
	}
	return *o.SubscriptionManagerId
}

// GetSubscriptionManagerIdOk returns a tuple with the SubscriptionManagerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateHostIn) GetSubscriptionManagerIdOk() (*string, bool) {
	if o == nil || o.SubscriptionManagerId == nil {
		return nil, false
	}
	return o.SubscriptionManagerId, true
}

// HasSubscriptionManagerId returns a boolean if a field has been set.
func (o *CreateHostIn) HasSubscriptionManagerId() bool {
	if o != nil && o.SubscriptionManagerId != nil {
		return true
	}

	return false
}

// SetSubscriptionManagerId gets a reference to the given string and assigns it to the SubscriptionManagerId field.
func (o *CreateHostIn) SetSubscriptionManagerId(v string) {
	o.SubscriptionManagerId = &v
}

// GetSystemProfile returns the SystemProfile field value if set, zero value otherwise.
func (o *CreateHostIn) GetSystemProfile() SystemProfile {
	if o == nil || o.SystemProfile == nil {
		var ret SystemProfile
		return ret
	}
	return *o.SystemProfile
}

// GetSystemProfileOk returns a tuple with the SystemProfile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateHostIn) GetSystemProfileOk() (*SystemProfile, bool) {
	if o == nil || o.SystemProfile == nil {
		return nil, false
	}
	return o.SystemProfile, true
}

// HasSystemProfile returns a boolean if a field has been set.
func (o *CreateHostIn) HasSystemProfile() bool {
	if o != nil && o.SystemProfile != nil {
		return true
	}

	return false
}

// SetSystemProfile gets a reference to the given SystemProfile and assigns it to the SystemProfile field.
func (o *CreateHostIn) SetSystemProfile(v SystemProfile) {
	o.SystemProfile = &v
}

func (o CreateHostIn) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["account"] = o.Account
	}
	if o.AnsibleHost != nil {
		toSerialize["ansible_host"] = o.AnsibleHost
	}
	if o.BiosUuid != nil {
		toSerialize["bios_uuid"] = o.BiosUuid
	}
	if o.DisplayName != nil {
		toSerialize["display_name"] = o.DisplayName
	}
	if o.ExternalId != nil {
		toSerialize["external_id"] = o.ExternalId
	}
	if o.Facts != nil {
		toSerialize["facts"] = o.Facts
	}
	if o.Fqdn != nil {
		toSerialize["fqdn"] = o.Fqdn
	}
	if o.InsightsId != nil {
		toSerialize["insights_id"] = o.InsightsId
	}
	if o.IpAddresses != nil {
		toSerialize["ip_addresses"] = o.IpAddresses
	}
	if o.MacAddresses != nil {
		toSerialize["mac_addresses"] = o.MacAddresses
	}
	if true {
		toSerialize["reporter"] = o.Reporter
	}
	if o.RhelMachineId != nil {
		toSerialize["rhel_machine_id"] = o.RhelMachineId
	}
	if o.SatelliteId != nil {
		toSerialize["satellite_id"] = o.SatelliteId
	}
	if true {
		toSerialize["stale_timestamp"] = o.StaleTimestamp
	}
	if o.SubscriptionManagerId != nil {
		toSerialize["subscription_manager_id"] = o.SubscriptionManagerId
	}
	if o.SystemProfile != nil {
		toSerialize["system_profile"] = o.SystemProfile
	}
	return json.Marshal(toSerialize)
}

type NullableCreateHostIn struct {
	value *CreateHostIn
	isSet bool
}

func (v NullableCreateHostIn) Get() *CreateHostIn {
	return v.value
}

func (v *NullableCreateHostIn) Set(val *CreateHostIn) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateHostIn) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateHostIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateHostIn(val *CreateHostIn) *NullableCreateHostIn {
	return &NullableCreateHostIn{value: val, isSet: true}
}

func (v NullableCreateHostIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateHostIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


