/*
 * Insights Host Inventory REST Interface
 *
 * REST interface for the Insights Platform Host Inventory application.
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package inventory

import (
	"encoding/json"
)

// SystemProfileByHostOutAllOf struct for SystemProfileByHostOutAllOf
type SystemProfileByHostOutAllOf struct {
	// Actual host search query result entries.
	Results []HostSystemProfileOut `json:"results"`
}

// NewSystemProfileByHostOutAllOf instantiates a new SystemProfileByHostOutAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemProfileByHostOutAllOf(results []HostSystemProfileOut, ) *SystemProfileByHostOutAllOf {
	this := SystemProfileByHostOutAllOf{}
	this.Results = results
	return &this
}

// NewSystemProfileByHostOutAllOfWithDefaults instantiates a new SystemProfileByHostOutAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemProfileByHostOutAllOfWithDefaults() *SystemProfileByHostOutAllOf {
	this := SystemProfileByHostOutAllOf{}
	return &this
}

// GetResults returns the Results field value
func (o *SystemProfileByHostOutAllOf) GetResults() []HostSystemProfileOut {
	if o == nil  {
		var ret []HostSystemProfileOut
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *SystemProfileByHostOutAllOf) GetResultsOk() (*[]HostSystemProfileOut, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Results, true
}

// SetResults sets field value
func (o *SystemProfileByHostOutAllOf) SetResults(v []HostSystemProfileOut) {
	o.Results = v
}

func (o SystemProfileByHostOutAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["results"] = o.Results
	}
	return json.Marshal(toSerialize)
}

type NullableSystemProfileByHostOutAllOf struct {
	value *SystemProfileByHostOutAllOf
	isSet bool
}

func (v NullableSystemProfileByHostOutAllOf) Get() *SystemProfileByHostOutAllOf {
	return v.value
}

func (v *NullableSystemProfileByHostOutAllOf) Set(val *SystemProfileByHostOutAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemProfileByHostOutAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemProfileByHostOutAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemProfileByHostOutAllOf(val *SystemProfileByHostOutAllOf) *NullableSystemProfileByHostOutAllOf {
	return &NullableSystemProfileByHostOutAllOf{value: val, isSet: true}
}

func (v NullableSystemProfileByHostOutAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemProfileByHostOutAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


