/*
 * Insights Host Inventory REST Interface
 *
 * REST interface for the Insights Platform Host Inventory application.
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package inventory

import (
	"encoding/json"
)

// SystemProfileDnfModules Representation of one DNF module
type SystemProfileDnfModules struct {
	Name *string `json:"name,omitempty"`
	Stream *string `json:"stream,omitempty"`
}

// NewSystemProfileDnfModules instantiates a new SystemProfileDnfModules object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemProfileDnfModules() *SystemProfileDnfModules {
	this := SystemProfileDnfModules{}
	return &this
}

// NewSystemProfileDnfModulesWithDefaults instantiates a new SystemProfileDnfModules object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemProfileDnfModulesWithDefaults() *SystemProfileDnfModules {
	this := SystemProfileDnfModules{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SystemProfileDnfModules) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfileDnfModules) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SystemProfileDnfModules) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SystemProfileDnfModules) SetName(v string) {
	o.Name = &v
}

// GetStream returns the Stream field value if set, zero value otherwise.
func (o *SystemProfileDnfModules) GetStream() string {
	if o == nil || o.Stream == nil {
		var ret string
		return ret
	}
	return *o.Stream
}

// GetStreamOk returns a tuple with the Stream field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfileDnfModules) GetStreamOk() (*string, bool) {
	if o == nil || o.Stream == nil {
		return nil, false
	}
	return o.Stream, true
}

// HasStream returns a boolean if a field has been set.
func (o *SystemProfileDnfModules) HasStream() bool {
	if o != nil && o.Stream != nil {
		return true
	}

	return false
}

// SetStream gets a reference to the given string and assigns it to the Stream field.
func (o *SystemProfileDnfModules) SetStream(v string) {
	o.Stream = &v
}

func (o SystemProfileDnfModules) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Stream != nil {
		toSerialize["stream"] = o.Stream
	}
	return json.Marshal(toSerialize)
}

type NullableSystemProfileDnfModules struct {
	value *SystemProfileDnfModules
	isSet bool
}

func (v NullableSystemProfileDnfModules) Get() *SystemProfileDnfModules {
	return v.value
}

func (v *NullableSystemProfileDnfModules) Set(val *SystemProfileDnfModules) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemProfileDnfModules) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemProfileDnfModules) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemProfileDnfModules(val *SystemProfileDnfModules) *NullableSystemProfileDnfModules {
	return &NullableSystemProfileDnfModules{value: val, isSet: true}
}

func (v NullableSystemProfileDnfModules) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemProfileDnfModules) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


