/*
 * Insights Host Inventory REST Interface
 *
 * REST interface for the Insights Platform Host Inventory application.
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package inventory

import (
	"encoding/json"
)

// SystemProfile Representation of the system profile fields
type SystemProfile struct {
	Arch *string `json:"arch,omitempty"`
	BiosReleaseDate *string `json:"bios_release_date,omitempty"`
	BiosVendor *string `json:"bios_vendor,omitempty"`
	BiosVersion *string `json:"bios_version,omitempty"`
	CapturedDate *string `json:"captured_date,omitempty"`
	CloudProvider *string `json:"cloud_provider,omitempty"`
	CoresPerSocket *int32 `json:"cores_per_socket,omitempty"`
	CpuFlags *[]string `json:"cpu_flags,omitempty"`
	DiskDevices *[]SystemProfileDiskDevices `json:"disk_devices,omitempty"`
	DnfModules *[]SystemProfileDnfModules `json:"dnf_modules,omitempty"`
	EnabledServices *[]string `json:"enabled_services,omitempty"`
	InfrastructureType *string `json:"infrastructure_type,omitempty"`
	InfrastructureVendor *string `json:"infrastructure_vendor,omitempty"`
	InsightsClientVersion *string `json:"insights_client_version,omitempty"`
	InsightsEggVersion *string `json:"insights_egg_version,omitempty"`
	InstalledPackages *[]string `json:"installed_packages,omitempty"`
	InstalledProducts *[]SystemProfileInstalledProducts `json:"installed_products,omitempty"`
	InstalledServices *[]string `json:"installed_services,omitempty"`
	KatelloAgentRunning *bool `json:"katello_agent_running,omitempty"`
	KernelModules *[]string `json:"kernel_modules,omitempty"`
	LastBootTime *string `json:"last_boot_time,omitempty"`
	NetworkInterfaces *[]SystemProfileNetworkInterfaces `json:"network_interfaces,omitempty"`
	NumberOfCpus *int32 `json:"number_of_cpus,omitempty"`
	NumberOfSockets *int32 `json:"number_of_sockets,omitempty"`
	OsKernelVersion *string `json:"os_kernel_version,omitempty"`
	OsRelease *string `json:"os_release,omitempty"`
	RunningProcesses *[]string `json:"running_processes,omitempty"`
	// List of SAP SIDs
	SapSids *[]string `json:"sap_sids,omitempty"`
	// Indicates if SAP is installed on the system
	SapSystem *bool `json:"sap_system,omitempty"`
	SatelliteManaged *bool `json:"satellite_managed,omitempty"`
	SubscriptionAutoAttach *string `json:"subscription_auto_attach,omitempty"`
	SubscriptionStatus *string `json:"subscription_status,omitempty"`
	SystemMemoryBytes *int64 `json:"system_memory_bytes,omitempty"`
	// Current profile resulting from command tuned-adm active
	TunedProfile *string `json:"tuned_profile,omitempty"`
	YumRepos *[]SystemProfileYumRepos `json:"yum_repos,omitempty"`
}

// NewSystemProfile instantiates a new SystemProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemProfile() *SystemProfile {
	this := SystemProfile{}
	return &this
}

// NewSystemProfileWithDefaults instantiates a new SystemProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemProfileWithDefaults() *SystemProfile {
	this := SystemProfile{}
	return &this
}

// GetArch returns the Arch field value if set, zero value otherwise.
func (o *SystemProfile) GetArch() string {
	if o == nil || o.Arch == nil {
		var ret string
		return ret
	}
	return *o.Arch
}

// GetArchOk returns a tuple with the Arch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetArchOk() (*string, bool) {
	if o == nil || o.Arch == nil {
		return nil, false
	}
	return o.Arch, true
}

// HasArch returns a boolean if a field has been set.
func (o *SystemProfile) HasArch() bool {
	if o != nil && o.Arch != nil {
		return true
	}

	return false
}

// SetArch gets a reference to the given string and assigns it to the Arch field.
func (o *SystemProfile) SetArch(v string) {
	o.Arch = &v
}

// GetBiosReleaseDate returns the BiosReleaseDate field value if set, zero value otherwise.
func (o *SystemProfile) GetBiosReleaseDate() string {
	if o == nil || o.BiosReleaseDate == nil {
		var ret string
		return ret
	}
	return *o.BiosReleaseDate
}

// GetBiosReleaseDateOk returns a tuple with the BiosReleaseDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetBiosReleaseDateOk() (*string, bool) {
	if o == nil || o.BiosReleaseDate == nil {
		return nil, false
	}
	return o.BiosReleaseDate, true
}

// HasBiosReleaseDate returns a boolean if a field has been set.
func (o *SystemProfile) HasBiosReleaseDate() bool {
	if o != nil && o.BiosReleaseDate != nil {
		return true
	}

	return false
}

// SetBiosReleaseDate gets a reference to the given string and assigns it to the BiosReleaseDate field.
func (o *SystemProfile) SetBiosReleaseDate(v string) {
	o.BiosReleaseDate = &v
}

// GetBiosVendor returns the BiosVendor field value if set, zero value otherwise.
func (o *SystemProfile) GetBiosVendor() string {
	if o == nil || o.BiosVendor == nil {
		var ret string
		return ret
	}
	return *o.BiosVendor
}

// GetBiosVendorOk returns a tuple with the BiosVendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetBiosVendorOk() (*string, bool) {
	if o == nil || o.BiosVendor == nil {
		return nil, false
	}
	return o.BiosVendor, true
}

// HasBiosVendor returns a boolean if a field has been set.
func (o *SystemProfile) HasBiosVendor() bool {
	if o != nil && o.BiosVendor != nil {
		return true
	}

	return false
}

// SetBiosVendor gets a reference to the given string and assigns it to the BiosVendor field.
func (o *SystemProfile) SetBiosVendor(v string) {
	o.BiosVendor = &v
}

// GetBiosVersion returns the BiosVersion field value if set, zero value otherwise.
func (o *SystemProfile) GetBiosVersion() string {
	if o == nil || o.BiosVersion == nil {
		var ret string
		return ret
	}
	return *o.BiosVersion
}

// GetBiosVersionOk returns a tuple with the BiosVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetBiosVersionOk() (*string, bool) {
	if o == nil || o.BiosVersion == nil {
		return nil, false
	}
	return o.BiosVersion, true
}

// HasBiosVersion returns a boolean if a field has been set.
func (o *SystemProfile) HasBiosVersion() bool {
	if o != nil && o.BiosVersion != nil {
		return true
	}

	return false
}

// SetBiosVersion gets a reference to the given string and assigns it to the BiosVersion field.
func (o *SystemProfile) SetBiosVersion(v string) {
	o.BiosVersion = &v
}

// GetCapturedDate returns the CapturedDate field value if set, zero value otherwise.
func (o *SystemProfile) GetCapturedDate() string {
	if o == nil || o.CapturedDate == nil {
		var ret string
		return ret
	}
	return *o.CapturedDate
}

// GetCapturedDateOk returns a tuple with the CapturedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetCapturedDateOk() (*string, bool) {
	if o == nil || o.CapturedDate == nil {
		return nil, false
	}
	return o.CapturedDate, true
}

// HasCapturedDate returns a boolean if a field has been set.
func (o *SystemProfile) HasCapturedDate() bool {
	if o != nil && o.CapturedDate != nil {
		return true
	}

	return false
}

// SetCapturedDate gets a reference to the given string and assigns it to the CapturedDate field.
func (o *SystemProfile) SetCapturedDate(v string) {
	o.CapturedDate = &v
}

// GetCloudProvider returns the CloudProvider field value if set, zero value otherwise.
func (o *SystemProfile) GetCloudProvider() string {
	if o == nil || o.CloudProvider == nil {
		var ret string
		return ret
	}
	return *o.CloudProvider
}

// GetCloudProviderOk returns a tuple with the CloudProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetCloudProviderOk() (*string, bool) {
	if o == nil || o.CloudProvider == nil {
		return nil, false
	}
	return o.CloudProvider, true
}

// HasCloudProvider returns a boolean if a field has been set.
func (o *SystemProfile) HasCloudProvider() bool {
	if o != nil && o.CloudProvider != nil {
		return true
	}

	return false
}

// SetCloudProvider gets a reference to the given string and assigns it to the CloudProvider field.
func (o *SystemProfile) SetCloudProvider(v string) {
	o.CloudProvider = &v
}

// GetCoresPerSocket returns the CoresPerSocket field value if set, zero value otherwise.
func (o *SystemProfile) GetCoresPerSocket() int32 {
	if o == nil || o.CoresPerSocket == nil {
		var ret int32
		return ret
	}
	return *o.CoresPerSocket
}

// GetCoresPerSocketOk returns a tuple with the CoresPerSocket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetCoresPerSocketOk() (*int32, bool) {
	if o == nil || o.CoresPerSocket == nil {
		return nil, false
	}
	return o.CoresPerSocket, true
}

// HasCoresPerSocket returns a boolean if a field has been set.
func (o *SystemProfile) HasCoresPerSocket() bool {
	if o != nil && o.CoresPerSocket != nil {
		return true
	}

	return false
}

// SetCoresPerSocket gets a reference to the given int32 and assigns it to the CoresPerSocket field.
func (o *SystemProfile) SetCoresPerSocket(v int32) {
	o.CoresPerSocket = &v
}

// GetCpuFlags returns the CpuFlags field value if set, zero value otherwise.
func (o *SystemProfile) GetCpuFlags() []string {
	if o == nil || o.CpuFlags == nil {
		var ret []string
		return ret
	}
	return *o.CpuFlags
}

// GetCpuFlagsOk returns a tuple with the CpuFlags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetCpuFlagsOk() (*[]string, bool) {
	if o == nil || o.CpuFlags == nil {
		return nil, false
	}
	return o.CpuFlags, true
}

// HasCpuFlags returns a boolean if a field has been set.
func (o *SystemProfile) HasCpuFlags() bool {
	if o != nil && o.CpuFlags != nil {
		return true
	}

	return false
}

// SetCpuFlags gets a reference to the given []string and assigns it to the CpuFlags field.
func (o *SystemProfile) SetCpuFlags(v []string) {
	o.CpuFlags = &v
}

// GetDiskDevices returns the DiskDevices field value if set, zero value otherwise.
func (o *SystemProfile) GetDiskDevices() []SystemProfileDiskDevices {
	if o == nil || o.DiskDevices == nil {
		var ret []SystemProfileDiskDevices
		return ret
	}
	return *o.DiskDevices
}

// GetDiskDevicesOk returns a tuple with the DiskDevices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetDiskDevicesOk() (*[]SystemProfileDiskDevices, bool) {
	if o == nil || o.DiskDevices == nil {
		return nil, false
	}
	return o.DiskDevices, true
}

// HasDiskDevices returns a boolean if a field has been set.
func (o *SystemProfile) HasDiskDevices() bool {
	if o != nil && o.DiskDevices != nil {
		return true
	}

	return false
}

// SetDiskDevices gets a reference to the given []SystemProfileDiskDevices and assigns it to the DiskDevices field.
func (o *SystemProfile) SetDiskDevices(v []SystemProfileDiskDevices) {
	o.DiskDevices = &v
}

// GetDnfModules returns the DnfModules field value if set, zero value otherwise.
func (o *SystemProfile) GetDnfModules() []SystemProfileDnfModules {
	if o == nil || o.DnfModules == nil {
		var ret []SystemProfileDnfModules
		return ret
	}
	return *o.DnfModules
}

// GetDnfModulesOk returns a tuple with the DnfModules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetDnfModulesOk() (*[]SystemProfileDnfModules, bool) {
	if o == nil || o.DnfModules == nil {
		return nil, false
	}
	return o.DnfModules, true
}

// HasDnfModules returns a boolean if a field has been set.
func (o *SystemProfile) HasDnfModules() bool {
	if o != nil && o.DnfModules != nil {
		return true
	}

	return false
}

// SetDnfModules gets a reference to the given []SystemProfileDnfModules and assigns it to the DnfModules field.
func (o *SystemProfile) SetDnfModules(v []SystemProfileDnfModules) {
	o.DnfModules = &v
}

// GetEnabledServices returns the EnabledServices field value if set, zero value otherwise.
func (o *SystemProfile) GetEnabledServices() []string {
	if o == nil || o.EnabledServices == nil {
		var ret []string
		return ret
	}
	return *o.EnabledServices
}

// GetEnabledServicesOk returns a tuple with the EnabledServices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetEnabledServicesOk() (*[]string, bool) {
	if o == nil || o.EnabledServices == nil {
		return nil, false
	}
	return o.EnabledServices, true
}

// HasEnabledServices returns a boolean if a field has been set.
func (o *SystemProfile) HasEnabledServices() bool {
	if o != nil && o.EnabledServices != nil {
		return true
	}

	return false
}

// SetEnabledServices gets a reference to the given []string and assigns it to the EnabledServices field.
func (o *SystemProfile) SetEnabledServices(v []string) {
	o.EnabledServices = &v
}

// GetInfrastructureType returns the InfrastructureType field value if set, zero value otherwise.
func (o *SystemProfile) GetInfrastructureType() string {
	if o == nil || o.InfrastructureType == nil {
		var ret string
		return ret
	}
	return *o.InfrastructureType
}

// GetInfrastructureTypeOk returns a tuple with the InfrastructureType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetInfrastructureTypeOk() (*string, bool) {
	if o == nil || o.InfrastructureType == nil {
		return nil, false
	}
	return o.InfrastructureType, true
}

// HasInfrastructureType returns a boolean if a field has been set.
func (o *SystemProfile) HasInfrastructureType() bool {
	if o != nil && o.InfrastructureType != nil {
		return true
	}

	return false
}

// SetInfrastructureType gets a reference to the given string and assigns it to the InfrastructureType field.
func (o *SystemProfile) SetInfrastructureType(v string) {
	o.InfrastructureType = &v
}

// GetInfrastructureVendor returns the InfrastructureVendor field value if set, zero value otherwise.
func (o *SystemProfile) GetInfrastructureVendor() string {
	if o == nil || o.InfrastructureVendor == nil {
		var ret string
		return ret
	}
	return *o.InfrastructureVendor
}

// GetInfrastructureVendorOk returns a tuple with the InfrastructureVendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetInfrastructureVendorOk() (*string, bool) {
	if o == nil || o.InfrastructureVendor == nil {
		return nil, false
	}
	return o.InfrastructureVendor, true
}

// HasInfrastructureVendor returns a boolean if a field has been set.
func (o *SystemProfile) HasInfrastructureVendor() bool {
	if o != nil && o.InfrastructureVendor != nil {
		return true
	}

	return false
}

// SetInfrastructureVendor gets a reference to the given string and assigns it to the InfrastructureVendor field.
func (o *SystemProfile) SetInfrastructureVendor(v string) {
	o.InfrastructureVendor = &v
}

// GetInsightsClientVersion returns the InsightsClientVersion field value if set, zero value otherwise.
func (o *SystemProfile) GetInsightsClientVersion() string {
	if o == nil || o.InsightsClientVersion == nil {
		var ret string
		return ret
	}
	return *o.InsightsClientVersion
}

// GetInsightsClientVersionOk returns a tuple with the InsightsClientVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetInsightsClientVersionOk() (*string, bool) {
	if o == nil || o.InsightsClientVersion == nil {
		return nil, false
	}
	return o.InsightsClientVersion, true
}

// HasInsightsClientVersion returns a boolean if a field has been set.
func (o *SystemProfile) HasInsightsClientVersion() bool {
	if o != nil && o.InsightsClientVersion != nil {
		return true
	}

	return false
}

// SetInsightsClientVersion gets a reference to the given string and assigns it to the InsightsClientVersion field.
func (o *SystemProfile) SetInsightsClientVersion(v string) {
	o.InsightsClientVersion = &v
}

// GetInsightsEggVersion returns the InsightsEggVersion field value if set, zero value otherwise.
func (o *SystemProfile) GetInsightsEggVersion() string {
	if o == nil || o.InsightsEggVersion == nil {
		var ret string
		return ret
	}
	return *o.InsightsEggVersion
}

// GetInsightsEggVersionOk returns a tuple with the InsightsEggVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetInsightsEggVersionOk() (*string, bool) {
	if o == nil || o.InsightsEggVersion == nil {
		return nil, false
	}
	return o.InsightsEggVersion, true
}

// HasInsightsEggVersion returns a boolean if a field has been set.
func (o *SystemProfile) HasInsightsEggVersion() bool {
	if o != nil && o.InsightsEggVersion != nil {
		return true
	}

	return false
}

// SetInsightsEggVersion gets a reference to the given string and assigns it to the InsightsEggVersion field.
func (o *SystemProfile) SetInsightsEggVersion(v string) {
	o.InsightsEggVersion = &v
}

// GetInstalledPackages returns the InstalledPackages field value if set, zero value otherwise.
func (o *SystemProfile) GetInstalledPackages() []string {
	if o == nil || o.InstalledPackages == nil {
		var ret []string
		return ret
	}
	return *o.InstalledPackages
}

// GetInstalledPackagesOk returns a tuple with the InstalledPackages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetInstalledPackagesOk() (*[]string, bool) {
	if o == nil || o.InstalledPackages == nil {
		return nil, false
	}
	return o.InstalledPackages, true
}

// HasInstalledPackages returns a boolean if a field has been set.
func (o *SystemProfile) HasInstalledPackages() bool {
	if o != nil && o.InstalledPackages != nil {
		return true
	}

	return false
}

// SetInstalledPackages gets a reference to the given []string and assigns it to the InstalledPackages field.
func (o *SystemProfile) SetInstalledPackages(v []string) {
	o.InstalledPackages = &v
}

// GetInstalledProducts returns the InstalledProducts field value if set, zero value otherwise.
func (o *SystemProfile) GetInstalledProducts() []SystemProfileInstalledProducts {
	if o == nil || o.InstalledProducts == nil {
		var ret []SystemProfileInstalledProducts
		return ret
	}
	return *o.InstalledProducts
}

// GetInstalledProductsOk returns a tuple with the InstalledProducts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetInstalledProductsOk() (*[]SystemProfileInstalledProducts, bool) {
	if o == nil || o.InstalledProducts == nil {
		return nil, false
	}
	return o.InstalledProducts, true
}

// HasInstalledProducts returns a boolean if a field has been set.
func (o *SystemProfile) HasInstalledProducts() bool {
	if o != nil && o.InstalledProducts != nil {
		return true
	}

	return false
}

// SetInstalledProducts gets a reference to the given []SystemProfileInstalledProducts and assigns it to the InstalledProducts field.
func (o *SystemProfile) SetInstalledProducts(v []SystemProfileInstalledProducts) {
	o.InstalledProducts = &v
}

// GetInstalledServices returns the InstalledServices field value if set, zero value otherwise.
func (o *SystemProfile) GetInstalledServices() []string {
	if o == nil || o.InstalledServices == nil {
		var ret []string
		return ret
	}
	return *o.InstalledServices
}

// GetInstalledServicesOk returns a tuple with the InstalledServices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetInstalledServicesOk() (*[]string, bool) {
	if o == nil || o.InstalledServices == nil {
		return nil, false
	}
	return o.InstalledServices, true
}

// HasInstalledServices returns a boolean if a field has been set.
func (o *SystemProfile) HasInstalledServices() bool {
	if o != nil && o.InstalledServices != nil {
		return true
	}

	return false
}

// SetInstalledServices gets a reference to the given []string and assigns it to the InstalledServices field.
func (o *SystemProfile) SetInstalledServices(v []string) {
	o.InstalledServices = &v
}

// GetKatelloAgentRunning returns the KatelloAgentRunning field value if set, zero value otherwise.
func (o *SystemProfile) GetKatelloAgentRunning() bool {
	if o == nil || o.KatelloAgentRunning == nil {
		var ret bool
		return ret
	}
	return *o.KatelloAgentRunning
}

// GetKatelloAgentRunningOk returns a tuple with the KatelloAgentRunning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetKatelloAgentRunningOk() (*bool, bool) {
	if o == nil || o.KatelloAgentRunning == nil {
		return nil, false
	}
	return o.KatelloAgentRunning, true
}

// HasKatelloAgentRunning returns a boolean if a field has been set.
func (o *SystemProfile) HasKatelloAgentRunning() bool {
	if o != nil && o.KatelloAgentRunning != nil {
		return true
	}

	return false
}

// SetKatelloAgentRunning gets a reference to the given bool and assigns it to the KatelloAgentRunning field.
func (o *SystemProfile) SetKatelloAgentRunning(v bool) {
	o.KatelloAgentRunning = &v
}

// GetKernelModules returns the KernelModules field value if set, zero value otherwise.
func (o *SystemProfile) GetKernelModules() []string {
	if o == nil || o.KernelModules == nil {
		var ret []string
		return ret
	}
	return *o.KernelModules
}

// GetKernelModulesOk returns a tuple with the KernelModules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetKernelModulesOk() (*[]string, bool) {
	if o == nil || o.KernelModules == nil {
		return nil, false
	}
	return o.KernelModules, true
}

// HasKernelModules returns a boolean if a field has been set.
func (o *SystemProfile) HasKernelModules() bool {
	if o != nil && o.KernelModules != nil {
		return true
	}

	return false
}

// SetKernelModules gets a reference to the given []string and assigns it to the KernelModules field.
func (o *SystemProfile) SetKernelModules(v []string) {
	o.KernelModules = &v
}

// GetLastBootTime returns the LastBootTime field value if set, zero value otherwise.
func (o *SystemProfile) GetLastBootTime() string {
	if o == nil || o.LastBootTime == nil {
		var ret string
		return ret
	}
	return *o.LastBootTime
}

// GetLastBootTimeOk returns a tuple with the LastBootTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetLastBootTimeOk() (*string, bool) {
	if o == nil || o.LastBootTime == nil {
		return nil, false
	}
	return o.LastBootTime, true
}

// HasLastBootTime returns a boolean if a field has been set.
func (o *SystemProfile) HasLastBootTime() bool {
	if o != nil && o.LastBootTime != nil {
		return true
	}

	return false
}

// SetLastBootTime gets a reference to the given string and assigns it to the LastBootTime field.
func (o *SystemProfile) SetLastBootTime(v string) {
	o.LastBootTime = &v
}

// GetNetworkInterfaces returns the NetworkInterfaces field value if set, zero value otherwise.
func (o *SystemProfile) GetNetworkInterfaces() []SystemProfileNetworkInterfaces {
	if o == nil || o.NetworkInterfaces == nil {
		var ret []SystemProfileNetworkInterfaces
		return ret
	}
	return *o.NetworkInterfaces
}

// GetNetworkInterfacesOk returns a tuple with the NetworkInterfaces field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetNetworkInterfacesOk() (*[]SystemProfileNetworkInterfaces, bool) {
	if o == nil || o.NetworkInterfaces == nil {
		return nil, false
	}
	return o.NetworkInterfaces, true
}

// HasNetworkInterfaces returns a boolean if a field has been set.
func (o *SystemProfile) HasNetworkInterfaces() bool {
	if o != nil && o.NetworkInterfaces != nil {
		return true
	}

	return false
}

// SetNetworkInterfaces gets a reference to the given []SystemProfileNetworkInterfaces and assigns it to the NetworkInterfaces field.
func (o *SystemProfile) SetNetworkInterfaces(v []SystemProfileNetworkInterfaces) {
	o.NetworkInterfaces = &v
}

// GetNumberOfCpus returns the NumberOfCpus field value if set, zero value otherwise.
func (o *SystemProfile) GetNumberOfCpus() int32 {
	if o == nil || o.NumberOfCpus == nil {
		var ret int32
		return ret
	}
	return *o.NumberOfCpus
}

// GetNumberOfCpusOk returns a tuple with the NumberOfCpus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetNumberOfCpusOk() (*int32, bool) {
	if o == nil || o.NumberOfCpus == nil {
		return nil, false
	}
	return o.NumberOfCpus, true
}

// HasNumberOfCpus returns a boolean if a field has been set.
func (o *SystemProfile) HasNumberOfCpus() bool {
	if o != nil && o.NumberOfCpus != nil {
		return true
	}

	return false
}

// SetNumberOfCpus gets a reference to the given int32 and assigns it to the NumberOfCpus field.
func (o *SystemProfile) SetNumberOfCpus(v int32) {
	o.NumberOfCpus = &v
}

// GetNumberOfSockets returns the NumberOfSockets field value if set, zero value otherwise.
func (o *SystemProfile) GetNumberOfSockets() int32 {
	if o == nil || o.NumberOfSockets == nil {
		var ret int32
		return ret
	}
	return *o.NumberOfSockets
}

// GetNumberOfSocketsOk returns a tuple with the NumberOfSockets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetNumberOfSocketsOk() (*int32, bool) {
	if o == nil || o.NumberOfSockets == nil {
		return nil, false
	}
	return o.NumberOfSockets, true
}

// HasNumberOfSockets returns a boolean if a field has been set.
func (o *SystemProfile) HasNumberOfSockets() bool {
	if o != nil && o.NumberOfSockets != nil {
		return true
	}

	return false
}

// SetNumberOfSockets gets a reference to the given int32 and assigns it to the NumberOfSockets field.
func (o *SystemProfile) SetNumberOfSockets(v int32) {
	o.NumberOfSockets = &v
}

// GetOsKernelVersion returns the OsKernelVersion field value if set, zero value otherwise.
func (o *SystemProfile) GetOsKernelVersion() string {
	if o == nil || o.OsKernelVersion == nil {
		var ret string
		return ret
	}
	return *o.OsKernelVersion
}

// GetOsKernelVersionOk returns a tuple with the OsKernelVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetOsKernelVersionOk() (*string, bool) {
	if o == nil || o.OsKernelVersion == nil {
		return nil, false
	}
	return o.OsKernelVersion, true
}

// HasOsKernelVersion returns a boolean if a field has been set.
func (o *SystemProfile) HasOsKernelVersion() bool {
	if o != nil && o.OsKernelVersion != nil {
		return true
	}

	return false
}

// SetOsKernelVersion gets a reference to the given string and assigns it to the OsKernelVersion field.
func (o *SystemProfile) SetOsKernelVersion(v string) {
	o.OsKernelVersion = &v
}

// GetOsRelease returns the OsRelease field value if set, zero value otherwise.
func (o *SystemProfile) GetOsRelease() string {
	if o == nil || o.OsRelease == nil {
		var ret string
		return ret
	}
	return *o.OsRelease
}

// GetOsReleaseOk returns a tuple with the OsRelease field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetOsReleaseOk() (*string, bool) {
	if o == nil || o.OsRelease == nil {
		return nil, false
	}
	return o.OsRelease, true
}

// HasOsRelease returns a boolean if a field has been set.
func (o *SystemProfile) HasOsRelease() bool {
	if o != nil && o.OsRelease != nil {
		return true
	}

	return false
}

// SetOsRelease gets a reference to the given string and assigns it to the OsRelease field.
func (o *SystemProfile) SetOsRelease(v string) {
	o.OsRelease = &v
}

// GetRunningProcesses returns the RunningProcesses field value if set, zero value otherwise.
func (o *SystemProfile) GetRunningProcesses() []string {
	if o == nil || o.RunningProcesses == nil {
		var ret []string
		return ret
	}
	return *o.RunningProcesses
}

// GetRunningProcessesOk returns a tuple with the RunningProcesses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetRunningProcessesOk() (*[]string, bool) {
	if o == nil || o.RunningProcesses == nil {
		return nil, false
	}
	return o.RunningProcesses, true
}

// HasRunningProcesses returns a boolean if a field has been set.
func (o *SystemProfile) HasRunningProcesses() bool {
	if o != nil && o.RunningProcesses != nil {
		return true
	}

	return false
}

// SetRunningProcesses gets a reference to the given []string and assigns it to the RunningProcesses field.
func (o *SystemProfile) SetRunningProcesses(v []string) {
	o.RunningProcesses = &v
}

// GetSapSids returns the SapSids field value if set, zero value otherwise.
func (o *SystemProfile) GetSapSids() []string {
	if o == nil || o.SapSids == nil {
		var ret []string
		return ret
	}
	return *o.SapSids
}

// GetSapSidsOk returns a tuple with the SapSids field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetSapSidsOk() (*[]string, bool) {
	if o == nil || o.SapSids == nil {
		return nil, false
	}
	return o.SapSids, true
}

// HasSapSids returns a boolean if a field has been set.
func (o *SystemProfile) HasSapSids() bool {
	if o != nil && o.SapSids != nil {
		return true
	}

	return false
}

// SetSapSids gets a reference to the given []string and assigns it to the SapSids field.
func (o *SystemProfile) SetSapSids(v []string) {
	o.SapSids = &v
}

// GetSapSystem returns the SapSystem field value if set, zero value otherwise.
func (o *SystemProfile) GetSapSystem() bool {
	if o == nil || o.SapSystem == nil {
		var ret bool
		return ret
	}
	return *o.SapSystem
}

// GetSapSystemOk returns a tuple with the SapSystem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetSapSystemOk() (*bool, bool) {
	if o == nil || o.SapSystem == nil {
		return nil, false
	}
	return o.SapSystem, true
}

// HasSapSystem returns a boolean if a field has been set.
func (o *SystemProfile) HasSapSystem() bool {
	if o != nil && o.SapSystem != nil {
		return true
	}

	return false
}

// SetSapSystem gets a reference to the given bool and assigns it to the SapSystem field.
func (o *SystemProfile) SetSapSystem(v bool) {
	o.SapSystem = &v
}

// GetSatelliteManaged returns the SatelliteManaged field value if set, zero value otherwise.
func (o *SystemProfile) GetSatelliteManaged() bool {
	if o == nil || o.SatelliteManaged == nil {
		var ret bool
		return ret
	}
	return *o.SatelliteManaged
}

// GetSatelliteManagedOk returns a tuple with the SatelliteManaged field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetSatelliteManagedOk() (*bool, bool) {
	if o == nil || o.SatelliteManaged == nil {
		return nil, false
	}
	return o.SatelliteManaged, true
}

// HasSatelliteManaged returns a boolean if a field has been set.
func (o *SystemProfile) HasSatelliteManaged() bool {
	if o != nil && o.SatelliteManaged != nil {
		return true
	}

	return false
}

// SetSatelliteManaged gets a reference to the given bool and assigns it to the SatelliteManaged field.
func (o *SystemProfile) SetSatelliteManaged(v bool) {
	o.SatelliteManaged = &v
}

// GetSubscriptionAutoAttach returns the SubscriptionAutoAttach field value if set, zero value otherwise.
func (o *SystemProfile) GetSubscriptionAutoAttach() string {
	if o == nil || o.SubscriptionAutoAttach == nil {
		var ret string
		return ret
	}
	return *o.SubscriptionAutoAttach
}

// GetSubscriptionAutoAttachOk returns a tuple with the SubscriptionAutoAttach field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetSubscriptionAutoAttachOk() (*string, bool) {
	if o == nil || o.SubscriptionAutoAttach == nil {
		return nil, false
	}
	return o.SubscriptionAutoAttach, true
}

// HasSubscriptionAutoAttach returns a boolean if a field has been set.
func (o *SystemProfile) HasSubscriptionAutoAttach() bool {
	if o != nil && o.SubscriptionAutoAttach != nil {
		return true
	}

	return false
}

// SetSubscriptionAutoAttach gets a reference to the given string and assigns it to the SubscriptionAutoAttach field.
func (o *SystemProfile) SetSubscriptionAutoAttach(v string) {
	o.SubscriptionAutoAttach = &v
}

// GetSubscriptionStatus returns the SubscriptionStatus field value if set, zero value otherwise.
func (o *SystemProfile) GetSubscriptionStatus() string {
	if o == nil || o.SubscriptionStatus == nil {
		var ret string
		return ret
	}
	return *o.SubscriptionStatus
}

// GetSubscriptionStatusOk returns a tuple with the SubscriptionStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetSubscriptionStatusOk() (*string, bool) {
	if o == nil || o.SubscriptionStatus == nil {
		return nil, false
	}
	return o.SubscriptionStatus, true
}

// HasSubscriptionStatus returns a boolean if a field has been set.
func (o *SystemProfile) HasSubscriptionStatus() bool {
	if o != nil && o.SubscriptionStatus != nil {
		return true
	}

	return false
}

// SetSubscriptionStatus gets a reference to the given string and assigns it to the SubscriptionStatus field.
func (o *SystemProfile) SetSubscriptionStatus(v string) {
	o.SubscriptionStatus = &v
}

// GetSystemMemoryBytes returns the SystemMemoryBytes field value if set, zero value otherwise.
func (o *SystemProfile) GetSystemMemoryBytes() int64 {
	if o == nil || o.SystemMemoryBytes == nil {
		var ret int64
		return ret
	}
	return *o.SystemMemoryBytes
}

// GetSystemMemoryBytesOk returns a tuple with the SystemMemoryBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetSystemMemoryBytesOk() (*int64, bool) {
	if o == nil || o.SystemMemoryBytes == nil {
		return nil, false
	}
	return o.SystemMemoryBytes, true
}

// HasSystemMemoryBytes returns a boolean if a field has been set.
func (o *SystemProfile) HasSystemMemoryBytes() bool {
	if o != nil && o.SystemMemoryBytes != nil {
		return true
	}

	return false
}

// SetSystemMemoryBytes gets a reference to the given int64 and assigns it to the SystemMemoryBytes field.
func (o *SystemProfile) SetSystemMemoryBytes(v int64) {
	o.SystemMemoryBytes = &v
}

// GetTunedProfile returns the TunedProfile field value if set, zero value otherwise.
func (o *SystemProfile) GetTunedProfile() string {
	if o == nil || o.TunedProfile == nil {
		var ret string
		return ret
	}
	return *o.TunedProfile
}

// GetTunedProfileOk returns a tuple with the TunedProfile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetTunedProfileOk() (*string, bool) {
	if o == nil || o.TunedProfile == nil {
		return nil, false
	}
	return o.TunedProfile, true
}

// HasTunedProfile returns a boolean if a field has been set.
func (o *SystemProfile) HasTunedProfile() bool {
	if o != nil && o.TunedProfile != nil {
		return true
	}

	return false
}

// SetTunedProfile gets a reference to the given string and assigns it to the TunedProfile field.
func (o *SystemProfile) SetTunedProfile(v string) {
	o.TunedProfile = &v
}

// GetYumRepos returns the YumRepos field value if set, zero value otherwise.
func (o *SystemProfile) GetYumRepos() []SystemProfileYumRepos {
	if o == nil || o.YumRepos == nil {
		var ret []SystemProfileYumRepos
		return ret
	}
	return *o.YumRepos
}

// GetYumReposOk returns a tuple with the YumRepos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfile) GetYumReposOk() (*[]SystemProfileYumRepos, bool) {
	if o == nil || o.YumRepos == nil {
		return nil, false
	}
	return o.YumRepos, true
}

// HasYumRepos returns a boolean if a field has been set.
func (o *SystemProfile) HasYumRepos() bool {
	if o != nil && o.YumRepos != nil {
		return true
	}

	return false
}

// SetYumRepos gets a reference to the given []SystemProfileYumRepos and assigns it to the YumRepos field.
func (o *SystemProfile) SetYumRepos(v []SystemProfileYumRepos) {
	o.YumRepos = &v
}

func (o SystemProfile) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Arch != nil {
		toSerialize["arch"] = o.Arch
	}
	if o.BiosReleaseDate != nil {
		toSerialize["bios_release_date"] = o.BiosReleaseDate
	}
	if o.BiosVendor != nil {
		toSerialize["bios_vendor"] = o.BiosVendor
	}
	if o.BiosVersion != nil {
		toSerialize["bios_version"] = o.BiosVersion
	}
	if o.CapturedDate != nil {
		toSerialize["captured_date"] = o.CapturedDate
	}
	if o.CloudProvider != nil {
		toSerialize["cloud_provider"] = o.CloudProvider
	}
	if o.CoresPerSocket != nil {
		toSerialize["cores_per_socket"] = o.CoresPerSocket
	}
	if o.CpuFlags != nil {
		toSerialize["cpu_flags"] = o.CpuFlags
	}
	if o.DiskDevices != nil {
		toSerialize["disk_devices"] = o.DiskDevices
	}
	if o.DnfModules != nil {
		toSerialize["dnf_modules"] = o.DnfModules
	}
	if o.EnabledServices != nil {
		toSerialize["enabled_services"] = o.EnabledServices
	}
	if o.InfrastructureType != nil {
		toSerialize["infrastructure_type"] = o.InfrastructureType
	}
	if o.InfrastructureVendor != nil {
		toSerialize["infrastructure_vendor"] = o.InfrastructureVendor
	}
	if o.InsightsClientVersion != nil {
		toSerialize["insights_client_version"] = o.InsightsClientVersion
	}
	if o.InsightsEggVersion != nil {
		toSerialize["insights_egg_version"] = o.InsightsEggVersion
	}
	if o.InstalledPackages != nil {
		toSerialize["installed_packages"] = o.InstalledPackages
	}
	if o.InstalledProducts != nil {
		toSerialize["installed_products"] = o.InstalledProducts
	}
	if o.InstalledServices != nil {
		toSerialize["installed_services"] = o.InstalledServices
	}
	if o.KatelloAgentRunning != nil {
		toSerialize["katello_agent_running"] = o.KatelloAgentRunning
	}
	if o.KernelModules != nil {
		toSerialize["kernel_modules"] = o.KernelModules
	}
	if o.LastBootTime != nil {
		toSerialize["last_boot_time"] = o.LastBootTime
	}
	if o.NetworkInterfaces != nil {
		toSerialize["network_interfaces"] = o.NetworkInterfaces
	}
	if o.NumberOfCpus != nil {
		toSerialize["number_of_cpus"] = o.NumberOfCpus
	}
	if o.NumberOfSockets != nil {
		toSerialize["number_of_sockets"] = o.NumberOfSockets
	}
	if o.OsKernelVersion != nil {
		toSerialize["os_kernel_version"] = o.OsKernelVersion
	}
	if o.OsRelease != nil {
		toSerialize["os_release"] = o.OsRelease
	}
	if o.RunningProcesses != nil {
		toSerialize["running_processes"] = o.RunningProcesses
	}
	if o.SapSids != nil {
		toSerialize["sap_sids"] = o.SapSids
	}
	if o.SapSystem != nil {
		toSerialize["sap_system"] = o.SapSystem
	}
	if o.SatelliteManaged != nil {
		toSerialize["satellite_managed"] = o.SatelliteManaged
	}
	if o.SubscriptionAutoAttach != nil {
		toSerialize["subscription_auto_attach"] = o.SubscriptionAutoAttach
	}
	if o.SubscriptionStatus != nil {
		toSerialize["subscription_status"] = o.SubscriptionStatus
	}
	if o.SystemMemoryBytes != nil {
		toSerialize["system_memory_bytes"] = o.SystemMemoryBytes
	}
	if o.TunedProfile != nil {
		toSerialize["tuned_profile"] = o.TunedProfile
	}
	if o.YumRepos != nil {
		toSerialize["yum_repos"] = o.YumRepos
	}
	return json.Marshal(toSerialize)
}

type NullableSystemProfile struct {
	value *SystemProfile
	isSet bool
}

func (v NullableSystemProfile) Get() *SystemProfile {
	return v.value
}

func (v *NullableSystemProfile) Set(val *SystemProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemProfile(val *SystemProfile) *NullableSystemProfile {
	return &NullableSystemProfile{value: val, isSet: true}
}

func (v NullableSystemProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


