/*
 * Insights Host Inventory REST Interface
 *
 * REST interface for the Insights Platform Host Inventory application.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventory
// CanonicalFactsInAllOf1 struct for CanonicalFactsInAllOf1
type CanonicalFactsInAllOf1 struct {
	BiosUuid string `json:"bios_uuid,omitempty"`
	ExternalId string `json:"external_id,omitempty"`
	Fqdn string `json:"fqdn,omitempty"`
	InsightsId string `json:"insights_id,omitempty"`
	IpAddresses []string `json:"ip_addresses,omitempty"`
	MacAddresses []string `json:"mac_addresses,omitempty"`
	RhelMachineId string `json:"rhel_machine_id,omitempty"`
	SatelliteId string `json:"satellite_id,omitempty"`
	SubscriptionManagerId string `json:"subscription_manager_id,omitempty"`
}
