/*
 * Insights Host Inventory REST Interface
 *
 * REST interface for the Insights Platform Host Inventory application.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventory
// SystemProfile Representation of the system profile fields
type SystemProfile struct {
	Arch string `json:"arch,omitempty"`
	BiosReleaseDate string `json:"bios_release_date,omitempty"`
	BiosVendor string `json:"bios_vendor,omitempty"`
	BiosVersion string `json:"bios_version,omitempty"`
	CapturedDate string `json:"captured_date,omitempty"`
	CloudProvider string `json:"cloud_provider,omitempty"`
	CoresPerSocket int32 `json:"cores_per_socket,omitempty"`
	CpuFlags []string `json:"cpu_flags,omitempty"`
	DiskDevices []SystemProfileDiskDevices `json:"disk_devices,omitempty"`
	DnfModules []SystemProfileDnfModules `json:"dnf_modules,omitempty"`
	EnabledServices []string `json:"enabled_services,omitempty"`
	InfrastructureType string `json:"infrastructure_type,omitempty"`
	InfrastructureVendor string `json:"infrastructure_vendor,omitempty"`
	InsightsClientVersion string `json:"insights_client_version,omitempty"`
	InsightsEggVersion string `json:"insights_egg_version,omitempty"`
	InstalledPackages []string `json:"installed_packages,omitempty"`
	InstalledProducts []SystemProfileInstalledProducts `json:"installed_products,omitempty"`
	InstalledServices []string `json:"installed_services,omitempty"`
	KatelloAgentRunning bool `json:"katello_agent_running,omitempty"`
	KernelModules []string `json:"kernel_modules,omitempty"`
	LastBootTime string `json:"last_boot_time,omitempty"`
	NetworkInterfaces []SystemProfileNetworkInterfaces `json:"network_interfaces,omitempty"`
	NumberOfCpus int32 `json:"number_of_cpus,omitempty"`
	NumberOfSockets int32 `json:"number_of_sockets,omitempty"`
	OsKernelVersion string `json:"os_kernel_version,omitempty"`
	OsRelease string `json:"os_release,omitempty"`
	RunningProcesses []string `json:"running_processes,omitempty"`
	// The instance number of the SAP HANA system
	SapInstanceNumber string `json:"sap_instance_number,omitempty"`
	// List of SAP SIDs
	SapSids []string `json:"sap_sids,omitempty"`
	// Indicates if SAP is installed on the system
	SapSystem bool `json:"sap_system,omitempty"`
	// The version of the SAP HANA lifecycle management program
	SapVersion string `json:"sap_version,omitempty"`
	SatelliteManaged bool `json:"satellite_managed,omitempty"`
	// The SELinux mode provided in the config file
	SelinuxConfigFile string `json:"selinux_config_file,omitempty"`
	// The current SELinux mode, either enforcing, permissive, or disabled
	SelinuxCurrentMode string `json:"selinux_current_mode,omitempty"`
	SubscriptionAutoAttach string `json:"subscription_auto_attach,omitempty"`
	SubscriptionStatus string `json:"subscription_status,omitempty"`
	SystemMemoryBytes int64 `json:"system_memory_bytes,omitempty"`
	// Current profile resulting from command tuned-adm active
	TunedProfile string `json:"tuned_profile,omitempty"`
	YumRepos []SystemProfileYumRepos `json:"yum_repos,omitempty"`
}
