/*
 * Insights Host Inventory REST Interface
 *
 * REST interface for the Insights Platform Host Inventory application.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventory
// SystemProfileYumRepos Representation of one yum repository
type SystemProfileYumRepos struct {
	BaseUrl string `json:"base_url,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
	Gpgcheck bool `json:"gpgcheck,omitempty"`
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}
