/*
 * Insights Host Inventory REST Interface
 *
 * REST interface for the Insights Platform Host Inventory application.
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package inventory

import (
	"encoding/json"
)

// SystemProfileDiskDevice Representation of one mounted device
type SystemProfileDiskDevice struct {
	Device *string `json:"device,omitempty"`
	// User-defined mount label
	Label *string `json:"label,omitempty"`
	// An arbitrary object that does not allow empty string keys.
	Options *map[string]OneOfmapobject `json:"options,omitempty"`
	// The mount point
	MountPoint *string `json:"mount_point,omitempty"`
	// The mount type
	Type *string `json:"type,omitempty"`
}

// NewSystemProfileDiskDevice instantiates a new SystemProfileDiskDevice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemProfileDiskDevice() *SystemProfileDiskDevice {
	this := SystemProfileDiskDevice{}
	return &this
}

// NewSystemProfileDiskDeviceWithDefaults instantiates a new SystemProfileDiskDevice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemProfileDiskDeviceWithDefaults() *SystemProfileDiskDevice {
	this := SystemProfileDiskDevice{}
	return &this
}

// GetDevice returns the Device field value if set, zero value otherwise.
func (o *SystemProfileDiskDevice) GetDevice() string {
	if o == nil || o.Device == nil {
		var ret string
		return ret
	}
	return *o.Device
}

// GetDeviceOk returns a tuple with the Device field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfileDiskDevice) GetDeviceOk() (*string, bool) {
	if o == nil || o.Device == nil {
		return nil, false
	}
	return o.Device, true
}

// HasDevice returns a boolean if a field has been set.
func (o *SystemProfileDiskDevice) HasDevice() bool {
	if o != nil && o.Device != nil {
		return true
	}

	return false
}

// SetDevice gets a reference to the given string and assigns it to the Device field.
func (o *SystemProfileDiskDevice) SetDevice(v string) {
	o.Device = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *SystemProfileDiskDevice) GetLabel() string {
	if o == nil || o.Label == nil {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfileDiskDevice) GetLabelOk() (*string, bool) {
	if o == nil || o.Label == nil {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *SystemProfileDiskDevice) HasLabel() bool {
	if o != nil && o.Label != nil {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *SystemProfileDiskDevice) SetLabel(v string) {
	o.Label = &v
}

// GetOptions returns the Options field value if set, zero value otherwise.
func (o *SystemProfileDiskDevice) GetOptions() map[string]OneOfmapobject {
	if o == nil || o.Options == nil {
		var ret map[string]OneOfmapobject
		return ret
	}
	return *o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfileDiskDevice) GetOptionsOk() (*map[string]OneOfmapobject, bool) {
	if o == nil || o.Options == nil {
		return nil, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *SystemProfileDiskDevice) HasOptions() bool {
	if o != nil && o.Options != nil {
		return true
	}

	return false
}

// SetOptions gets a reference to the given map[string]OneOfmapobject and assigns it to the Options field.
func (o *SystemProfileDiskDevice) SetOptions(v map[string]OneOfmapobject) {
	o.Options = &v
}

// GetMountPoint returns the MountPoint field value if set, zero value otherwise.
func (o *SystemProfileDiskDevice) GetMountPoint() string {
	if o == nil || o.MountPoint == nil {
		var ret string
		return ret
	}
	return *o.MountPoint
}

// GetMountPointOk returns a tuple with the MountPoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfileDiskDevice) GetMountPointOk() (*string, bool) {
	if o == nil || o.MountPoint == nil {
		return nil, false
	}
	return o.MountPoint, true
}

// HasMountPoint returns a boolean if a field has been set.
func (o *SystemProfileDiskDevice) HasMountPoint() bool {
	if o != nil && o.MountPoint != nil {
		return true
	}

	return false
}

// SetMountPoint gets a reference to the given string and assigns it to the MountPoint field.
func (o *SystemProfileDiskDevice) SetMountPoint(v string) {
	o.MountPoint = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *SystemProfileDiskDevice) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemProfileDiskDevice) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *SystemProfileDiskDevice) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *SystemProfileDiskDevice) SetType(v string) {
	o.Type = &v
}

func (o SystemProfileDiskDevice) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Device != nil {
		toSerialize["device"] = o.Device
	}
	if o.Label != nil {
		toSerialize["label"] = o.Label
	}
	if o.Options != nil {
		toSerialize["options"] = o.Options
	}
	if o.MountPoint != nil {
		toSerialize["mount_point"] = o.MountPoint
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableSystemProfileDiskDevice struct {
	value *SystemProfileDiskDevice
	isSet bool
}

func (v NullableSystemProfileDiskDevice) Get() *SystemProfileDiskDevice {
	return v.value
}

func (v *NullableSystemProfileDiskDevice) Set(val *SystemProfileDiskDevice) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemProfileDiskDevice) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemProfileDiskDevice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemProfileDiskDevice(val *SystemProfileDiskDevice) *NullableSystemProfileDiskDevice {
	return &NullableSystemProfileDiskDevice{value: val, isSet: true}
}

func (v NullableSystemProfileDiskDevice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemProfileDiskDevice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


