/*
 * Insights Host Inventory REST Interface
 *
 * REST interface for the Insights Platform Host Inventory application.
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package inventory

import (
	"encoding/json"
)

// TagCountOut struct for TagCountOut
type TagCountOut struct {
	// The number of items on the current page
	Count int32 `json:"count"`
	// The page number
	Page int32 `json:"page"`
	// The number of items to return per page
	PerPage int32 `json:"per_page"`
	// Total number of items
	Total int32 `json:"total"`
	// The list of tags on the systems
	Results *map[string]int32 `json:"results,omitempty"`
}

// NewTagCountOut instantiates a new TagCountOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagCountOut(count int32, page int32, perPage int32, total int32, ) *TagCountOut {
	this := TagCountOut{}
	this.Count = count
	this.Page = page
	this.PerPage = perPage
	this.Total = total
	return &this
}

// NewTagCountOutWithDefaults instantiates a new TagCountOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagCountOutWithDefaults() *TagCountOut {
	this := TagCountOut{}
	return &this
}

// GetCount returns the Count field value
func (o *TagCountOut) GetCount() int32 {
	if o == nil  {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *TagCountOut) GetCountOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *TagCountOut) SetCount(v int32) {
	o.Count = v
}

// GetPage returns the Page field value
func (o *TagCountOut) GetPage() int32 {
	if o == nil  {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *TagCountOut) GetPageOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *TagCountOut) SetPage(v int32) {
	o.Page = v
}

// GetPerPage returns the PerPage field value
func (o *TagCountOut) GetPerPage() int32 {
	if o == nil  {
		var ret int32
		return ret
	}

	return o.PerPage
}

// GetPerPageOk returns a tuple with the PerPage field value
// and a boolean to check if the value has been set.
func (o *TagCountOut) GetPerPageOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PerPage, true
}

// SetPerPage sets field value
func (o *TagCountOut) SetPerPage(v int32) {
	o.PerPage = v
}

// GetTotal returns the Total field value
func (o *TagCountOut) GetTotal() int32 {
	if o == nil  {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *TagCountOut) GetTotalOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *TagCountOut) SetTotal(v int32) {
	o.Total = v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *TagCountOut) GetResults() map[string]int32 {
	if o == nil || o.Results == nil {
		var ret map[string]int32
		return ret
	}
	return *o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TagCountOut) GetResultsOk() (*map[string]int32, bool) {
	if o == nil || o.Results == nil {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *TagCountOut) HasResults() bool {
	if o != nil && o.Results != nil {
		return true
	}

	return false
}

// SetResults gets a reference to the given map[string]int32 and assigns it to the Results field.
func (o *TagCountOut) SetResults(v map[string]int32) {
	o.Results = &v
}

func (o TagCountOut) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["count"] = o.Count
	}
	if true {
		toSerialize["page"] = o.Page
	}
	if true {
		toSerialize["per_page"] = o.PerPage
	}
	if true {
		toSerialize["total"] = o.Total
	}
	if o.Results != nil {
		toSerialize["results"] = o.Results
	}
	return json.Marshal(toSerialize)
}

type NullableTagCountOut struct {
	value *TagCountOut
	isSet bool
}

func (v NullableTagCountOut) Get() *TagCountOut {
	return v.value
}

func (v *NullableTagCountOut) Set(val *TagCountOut) {
	v.value = val
	v.isSet = true
}

func (v NullableTagCountOut) IsSet() bool {
	return v.isSet
}

func (v *NullableTagCountOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagCountOut(val *TagCountOut) *NullableTagCountOut {
	return &NullableTagCountOut{value: val, isSet: true}
}

func (v NullableTagCountOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagCountOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


