/*
 * Insights Host Inventory REST Interface
 *
 * REST interface for the Insights Platform Host Inventory application.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventory
// CreateCheckInAllOf struct for CreateCheckInAllOf
type CreateCheckInAllOf struct {
	// How long from now to expect another check-in (in minutes).
	CheckinFrequency int32 `json:"checkin_frequency,omitempty"`
}
