/*
 * Insights Host Inventory REST Interface
 *
 * REST interface for the Insights Platform Host Inventory application.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventory
// CreateHostOutAllOf struct for CreateHostOutAllOf
type CreateHostOutAllOf struct {
	// A Red Hat Account number that owns the host.
	Account string `json:"account"`
	// The ansible host name for remediations
	AnsibleHost *string `json:"ansible_host,omitempty"`
	// A timestamp when the entry was created.
	Created string `json:"created,omitempty"`
	// Timestamp from which the host is considered deleted.
	CulledTimestamp *string `json:"culled_timestamp,omitempty"`
	// A host’s human-readable display name, e.g. in a form of a domain name.
	DisplayName *string `json:"display_name,omitempty"`
	// A set of facts belonging to the host.
	Facts []map[string]interface{} `json:"facts,omitempty"`
	// A durable and reliable platform-wide host identifier. Applications should use this identifier to reference hosts.
	Id string `json:"id,omitempty"`
	// Reporting source of the host. Used when updating the stale_timestamp.
	Reporter *string `json:"reporter,omitempty"`
	// Timestamp from which the host is considered stale.
	StaleTimestamp *string `json:"stale_timestamp,omitempty"`
	// Timestamp from which the host is considered too stale to be listed without an explicit toggle.
	StaleWarningTimestamp *string `json:"stale_warning_timestamp,omitempty"`
	// A timestamp when the entry was last updated.
	Updated string `json:"updated,omitempty"`
}
