/*
 * Role Based Access Control
 *
 * The API for Role Based Access Control.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rbac
// PaginationLinks struct for PaginationLinks
type PaginationLinks struct {
	First string `json:"first,omitempty"`
	Previous string `json:"previous,omitempty"`
	Next string `json:"next,omitempty"`
	Last string `json:"last,omitempty"`
}
