/*
 * Role Based Access Control
 *
 * The API for Role Based Access Control.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rbac
// PolicyExtendedAllOf struct for PolicyExtendedAllOf
type PolicyExtendedAllOf struct {
	Group GroupOut `json:"group"`
	Roles []RoleOut `json:"roles"`
}
