/*
 * Role Based Access Control
 *
 * The API for Role Based Access Control.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rbac
// Group struct for Group
type Group struct {
	Name string `json:"name"`
	Description string `json:"description,omitempty"`
}
