/*
 * Role Based Access Control
 *
 * The API for Role Based Access Control.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rbac
// GroupOutAllOf struct for GroupOutAllOf
type GroupOutAllOf struct {
	PrincipalCount int32 `json:"principalCount,omitempty"`
	RoleCount int32 `json:"roleCount,omitempty"`
	System bool `json:"system,omitempty"`
	PlatformDefault bool `json:"platform_default,omitempty"`
}
