/*
 * Role Based Access Control
 *
 * The API for Role Based Access Control.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rbac
// GroupWithPrincipalsAndRolesAllOf struct for GroupWithPrincipalsAndRolesAllOf
type GroupWithPrincipalsAndRolesAllOf struct {
	Principals []Principal `json:"principals"`
	Roles []RoleOut `json:"roles"`
}
