/*
 * Role Based Access Control
 *
 * The API for Role Based Access Control.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rbac
// PolicyIn struct for PolicyIn
type PolicyIn struct {
	Name string `json:"name"`
	Description string `json:"description,omitempty"`
	Group string `json:"group"`
	Roles []string `json:"roles"`
}
