/*
 * Role Based Access Control
 *
 * The API for Role Based Access Control.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rbac
// Error struct for Error
type Error struct {
	Errors []map[string]interface{} `json:"errors"`
}
