/*
 * Role Based Access Control
 *
 * The API for Role Based Access Control.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rbac
// PolicyInAllOf struct for PolicyInAllOf
type PolicyInAllOf struct {
	Group string `json:"group"`
	Roles []string `json:"roles"`
}
