/*
 * Role Based Access Control
 *
 * The API for Role Based Access Control.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rbac
// Principal struct for Principal
type Principal struct {
	Username string `json:"username"`
	Email string `json:"email"`
	FirstName string `json:"first_name,omitempty"`
	LastName string `json:"last_name,omitempty"`
}
