/*
 * Role Based Access Control
 *
 * The API for Role Based Access Control.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rbac
// Uuid struct for Uuid
type Uuid struct {
	Uuid string `json:"uuid"`
}
