/*
 * Role Based Access Control
 *
 * The API for Role Based Access Control.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rbac
// PrincipalPaginationAllOf struct for PrincipalPaginationAllOf
type PrincipalPaginationAllOf struct {
	Data []Principal `json:"data"`
}
