/*
 * Role Based Access Control
 *
 * The API for Role Based Access Control.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rbac
// RoleOutDynamicAllOf struct for RoleOutDynamicAllOf
type RoleOutDynamicAllOf struct {
	PolicyCount int32 `json:"policyCount"`
	AccessCount int32 `json:"accessCount"`
	Applications []string `json:"applications"`
	System bool `json:"system"`
	PlatformDefault bool `json:"platform_default"`
	GroupsInCount int32 `json:"groups_in_count,omitempty"`
	GroupsIn []AdditionalGroup `json:"groups_in,omitempty"`
}
