/*
 * Role Based Access Control
 *
 * The API for Role Based Access Control.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rbac
// GroupOut struct for GroupOut
type GroupOut struct {
	Name string `json:"name"`
	Description string `json:"description,omitempty"`
	Uuid string `json:"uuid"`
	Created string `json:"created"`
	Modified string `json:"modified"`
	PrincipalCount int32 `json:"principalCount,omitempty"`
	RoleCount int32 `json:"roleCount,omitempty"`
	System bool `json:"system,omitempty"`
	PlatformDefault bool `json:"platform_default,omitempty"`
}
