/*
 * Role Based Access Control
 *
 * The API for Role Based Access Control.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rbac
// InlineResponse2001 struct for InlineResponse2001
type InlineResponse2001 struct {
	Data []AccessPagination `json:"data"`
}
