/*
 * Role Based Access Control
 *
 * The API for Role Based Access Control.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rbac
// GroupWithPrincipalsAndRoles struct for GroupWithPrincipalsAndRoles
type GroupWithPrincipalsAndRoles struct {
	Name string `json:"name"`
	Description string `json:"description,omitempty"`
	Uuid string `json:"uuid"`
	Created string `json:"created"`
	Modified string `json:"modified"`
	Principals []Principal `json:"principals"`
	Roles []RoleOut `json:"roles"`
}
